#ifndef FFIER_TEST_H
#define FFIER_TEST_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

typedef void* FtWidget;
typedef void* FtGadget;
typedef void* FtConfig;
typedef void* FtGizmo;
typedef void* FtGizmoBuilder;
typedef void* FtView;
typedef void* FtPipeline;

/* Caller must ensure data is valid UTF-8 */
typedef struct {
    const char* data;
    uintptr_t len;
} FtStr;

/* Caller must ensure data is a valid UTF-8 path */
typedef FtStr FtPath;

typedef struct {
    const uint8_t* data;
    uintptr_t len;
} FtBytes;

#define FT_STR(s) ((FtStr){ .data = (s), .len = strlen(s) })
#if defined(__GNUC__)
#define FT_BYTES(arr) ({ \
    _Static_assert( \
        !__builtin_types_compatible_p(typeof(arr), typeof(&(arr)[0])), \
        "FT_BYTES() requires an array, not a pointer"); \
    ((FtBytes){ .data = (const uint8_t*)(arr), .len = sizeof(arr) }); \
})
#else
#define FT_BYTES(arr) \
    ((FtBytes){ .data = (const uint8_t*)(arr), .len = sizeof(arr) })
#endif
/* Header auto-generated by ffier */

/* TestError --------------------------------------------------------- */

typedef struct {
    uint64_t code;
    char* _msg; /* private */
} FtTestError;

#define FT_TEST_ERROR_NOT_FOUND 1
#define FT_TEST_ERROR_CUSTOM_MESSAGE 2
#define FT_TEST_ERROR_INVALID_INPUT 3

const char* ft_test_error_message(const FtTestError* err);
void ft_test_error_free(FtTestError* err);

/* Widget ------------------------------------------------------------ */

/**
 * Create a new widget with default values.
 */
FtWidget ft_widget_new(void);
/**
 * Create a widget with a given name.
 *
 * @param name
 */
FtWidget ft_widget_with_name(FtStr name);
/**
 * Get the current count.
 */
int32_t ft_widget_get_count(FtWidget handle);
/**
 * Set the count.
 *
 * @param n
 */
void ft_widget_set_count(FtWidget handle, int32_t n);
/**
 * Get the widget name.
 */
FtStr ft_widget_name(FtWidget handle);
/**
 * Get the raw name bytes.
 */
FtBytes ft_widget_data(FtWidget handle);
/**
 * Echo back the given string (zero-copy borrow passthrough).
 *
 * @param s
 */
FtStr ft_widget_echo(FtWidget handle, FtStr s);
/**
 * Check if the widget is active.
 */
bool ft_widget_is_active(FtWidget handle);
/**
 * Negate a 64-bit integer.
 *
 * @param v
 */
int64_t ft_widget_negate(FtWidget handle, int64_t v);
/**
 * Validate internal state (always succeeds for default widget).
 *
 * @return FtTestError with code 0 on success, error code on failure.
 */
FtTestError ft_widget_validate(FtWidget handle);
/**
 * Parse a count value from the name length, returning error if name matches trigger.
 *
 * @param s
 * @param[out] result
 * @return FtTestError with code 0 on success, error code on failure.
 */
FtTestError ft_widget_parse_count(FtWidget handle, FtStr s, int32_t* result);
/**
 * Describe a code as a string.
 *
 * @param code
 * @param[out] result
 * @return FtTestError with code 0 on success, error code on failure.
 */
FtTestError ft_widget_describe(FtWidget handle, int32_t code, FtStr* result);
/**
 * Always fails with an error.
 *
 * @return FtTestError with code 0 on success, error code on failure.
 */
FtTestError ft_widget_fail_always(FtWidget handle);
/**
 * Always fails with an error (value variant).
 *
 * @param[out] result
 * @return FtTestError with code 0 on success, error code on failure.
 */
FtTestError ft_widget_fail_with_value(FtWidget handle, int32_t* result);
/**
 * Set tags from a string slice.
 *
 * @param tags
 */
void ft_widget_set_tags(FtWidget handle, const FtStr* tags, uintptr_t tags_len);
/**
 * Get joined tags.
 */
FtStr ft_widget_tags_joined(FtWidget handle);
/**
 * Create a new gadget with the widget's count as initial value.
 */
FtGadget ft_widget_create_gadget(FtWidget handle);
/**
 * Try to create a gadget; fails if ok is false.
 *
 * @param ok
 * @param[out] result
 * @return FtTestError with code 0 on success, error code on failure.
 */
FtTestError ft_widget_try_create_gadget(FtWidget handle, bool ok, FtGadget* result);
/**
 * Read a gadget's value.
 *
 * @param g
 */
int32_t ft_widget_read_gadget(FtWidget handle, FtGadget g);
/**
 * Update a gadget's value.
 *
 * @param g
 * @param v
 */
void ft_widget_update_gadget(FtWidget handle, FtGadget g, int32_t v);
/**
 * Consume the widget (by-value self, void return).
 */
void ft_widget_consume(FtWidget handle);
/**
 * Get the raw fd number from a borrowed fd.
 *
 * @param fd
 */
int32_t ft_widget_fd_number(FtWidget handle, int fd);
/**
 * Duplicate a file descriptor (returns owned fd).
 *
 * @param fd
 */
int ft_widget_dup_fd(FtWidget handle, int fd);
void ft_widget_destroy(FtWidget handle);

/* Gadget ------------------------------------------------------------ */

/**
 * Get the gadget value.
 */
int32_t ft_gadget_get(FtGadget handle);
void ft_gadget_destroy(FtGadget handle);

/* Config ------------------------------------------------------------ */

/**
 * Create a new config.
 */
FtConfig ft_config_new(void);
/**
 * Set the name (builder pattern: consumes self, returns Self).
 *
 * @param name
 */
void ft_config_set_name(FtConfig* handle, FtStr name);
/**
 * Set the size (builder pattern).
 *
 * @param size
 */
void ft_config_set_size(FtConfig* handle, int32_t size);
/**
 * Validate and return self, or error if name is empty.
 *
 * @return FtTestError with code 0 on success, error code on failure.
 */
FtTestError ft_config_validated(FtConfig* handle);
/**
 * Get the config name.
 */
FtStr ft_config_get_name(FtConfig handle);
/**
 * Get the config size.
 */
int32_t ft_config_get_size(FtConfig handle);
void ft_config_destroy(FtConfig handle);

/* Gizmo ------------------------------------------------------------- */

/**
 * Get the gizmo name.
 */
FtStr ft_gizmo_name(FtGizmo handle);
/**
 * Get the gizmo size.
 */
int32_t ft_gizmo_size(FtGizmo handle);
void ft_gizmo_destroy(FtGizmo handle);

/* GizmoBuilder ------------------------------------------------------ */

/**
 * Create a new gizmo builder.
 */
FtGizmoBuilder ft_gizmo_builder_new(void);
/**
 * Set the gizmo name.
 *
 * @param name
 */
void ft_gizmo_builder_set_name(FtGizmoBuilder handle, FtStr name);
/**
 * Set the gizmo size.
 *
 * @param size
 */
void ft_gizmo_builder_set_size(FtGizmoBuilder handle, int32_t size);
/**
 * Build the gizmo (consumes builder, returns different type).
 */
FtGizmo ft_gizmo_builder_build(FtGizmoBuilder handle);
/**
 * Try to build the gizmo; fails if name is empty.
 *
 * @param[out] result
 * @return FtTestError with code 0 on success, error code on failure.
 */
FtTestError ft_gizmo_builder_try_build(FtGizmoBuilder handle, FtGizmo* result);
void ft_gizmo_builder_destroy(FtGizmoBuilder handle);

/* View -------------------------------------------------------------- */

/**
 * Create a view that borrows a widget.
 *
 * @param source
 * @note `source` is borrowed by the returned `FtView`. It must not be directly modified or destroyed while the `FtView` is alive.
 */
FtView ft_view_create(FtWidget source);
/**
 * Read the source widget's count through the borrow.
 */
int32_t ft_view_source_count(FtView handle);
/**
 * Set the view label.
 *
 * @param label
 */
void ft_view_set_label(FtView handle, FtStr label);
/**
 * Get the view label.
 */
FtStr ft_view_label(FtView handle);
void ft_view_destroy(FtView handle);

/* Pipeline ---------------------------------------------------------- */

typedef void* FtProcessor; /* FtVtableProcessor */
/**
 * Create a new pipeline.
 */
FtPipeline ft_pipeline_new(void);
/**
 * Run a processor on the given input.
 *
 * @param proc
 * @param input
 */
void ft_pipeline_run(FtPipeline handle, FtProcessor proc, int32_t input);
/**
 * Get the number of results.
 */
int32_t ft_pipeline_result_count(FtPipeline handle);
/**
 * Get the last result, or error if empty.
 *
 * @param[out] result
 * @return FtTestError with code 0 on success, error code on failure.
 */
FtTestError ft_pipeline_last_result(FtPipeline handle, int32_t* result);
void ft_pipeline_destroy(FtPipeline handle);

/* VtableProcessor --------------------------------------------------- */

typedef struct {
    int32_t (*process)(void* self_data, int32_t input);
    FtStr (*name)(void* self_data);
    void (*on_notify)(void* self_data, int32_t code);
    void (*drop)(void* self_data);
} FtProcessorVtable;

void* ft_processor_from_vtable(void* user_data, const FtProcessorVtable* vtable);
#endif /* FFIER_TEST_H */
