// Generates Rust client binding source code.
// Output is piped through rustfmt and saved to tests/lib-via-cdylib/src/generated.rs

ffier_test_lib::__ffier_ft_library!(ffier_gen_rust::generate);

fn main() {
    println!("// Auto-generated by gen-rust-client. Do not edit manually.");
    println!("// Regenerate with: just gen-rust-client");
    println!();
    println!("#[allow(unused_imports)]");
    println!("use std::os::unix::io::{{AsRawFd, BorrowedFd, FromRawFd, OwnedFd}};");
    println!();
    print!("{FFIER_ALL_CLIENT_SRC}");
}
