// Generates Rust client binding source code.
// Output is piped through rustfmt and saved to tests/lib-via-cdylib/src/generated.rs

ffier_test_lib::ffier_meta_op_test_error!("ft", ffier_gen_rust::generate_client_source);
ffier_test_lib::ffier_meta_op_widget!("ft", ffier_gen_rust::generate_client_source);
ffier_test_lib::ffier_meta_op_gadget!("ft", ffier_gen_rust::generate_client_source);
ffier_test_lib::ffier_meta_op_config!("ft", ffier_gen_rust::generate_client_source);
ffier_test_lib::ffier_meta_op_gizmo!("ft", ffier_gen_rust::generate_client_source);
ffier_test_lib::ffier_meta_op_gizmo_builder!("ft", ffier_gen_rust::generate_client_source);
ffier_test_lib::ffier_meta_op_view!("ft", ffier_gen_rust::generate_client_source);
ffier_test_lib::ffier_meta_op_pipeline!("ft", ffier_gen_rust::generate_client_source);
ffier_test_lib::ffier_meta_op_vtable_processor!("ft", ffier_gen_rust::generate_client_source);
ffier_test_lib::ffier_meta_op_apple!("ft", ffier_gen_rust::generate_client_source);
ffier_test_lib::ffier_meta_op_orange!("ft", ffier_gen_rust::generate_client_source);
ffier_test_lib::ffier_meta_op_mixer!("ft", ffier_gen_rust::generate_client_source);

fn main() {
    println!("// Auto-generated by gen-rust-client. Do not edit manually.");
    println!("// Regenerate with: just gen-rust-client");
    println!();
    println!("#[allow(unused_imports)]");
    println!("use std::os::unix::io::{{AsRawFd, BorrowedFd, FromRawFd, OwnedFd}};");
    println!();
    print!("{FFIER_SRC_TEST_ERROR}");
    print!("{FFIER_SRC_WIDGET}");
    print!("{FFIER_SRC_GADGET}");
    print!("{FFIER_SRC_CONFIG}");
    print!("{FFIER_SRC_GIZMO}");
    print!("{FFIER_SRC_GIZMO_BUILDER}");
    print!("{FFIER_SRC_VIEW}");
    print!("{FFIER_SRC_PIPELINE}");
    print!("{FFIER_SRC_VTABLE_PROCESSOR}");
    print!("{FFIER_SRC_APPLE}");
    print!("{FFIER_SRC_ORANGE}");
    print!("{FFIER_SRC_MIXER}");
}
