// Generates Rust client binding source code.
// Output is piped through rustfmt and saved to tests/lib-via-cdylib/src/generated.rs

ffier_test_lib::__ffier_meta_test_error!("ft_", "Ft", "FT_", ffier::generate_client_source);
ffier_test_lib::__ffier_meta_widget!(ffier::generate_client_source);
ffier_test_lib::__ffier_meta_gadget!(ffier::generate_client_source);
ffier_test_lib::__ffier_meta_config!(ffier::generate_client_source);
ffier_test_lib::__ffier_meta_gizmo!(ffier::generate_client_source);
ffier_test_lib::__ffier_meta_gizmo_builder!(ffier::generate_client_source);
ffier_test_lib::__ffier_meta_view!(ffier::generate_client_source);
ffier_test_lib::__ffier_meta_pipeline!(ffier::generate_client_source);
ffier_test_lib::__ffier_meta_vtable_processor!(ffier::generate_client_source);

fn main() {
    println!("// Auto-generated by gen-rust-client. Do not edit manually.");
    println!("// Regenerate with: just gen-rust-client");
    println!();
    println!("#[allow(unused_imports)]");
    println!("use std::os::unix::io::{{AsRawFd, BorrowedFd, FromRawFd, OwnedFd}};");
    println!();
    print!("{__FFIER_SRC_0}");
    print!("{__FFIER_SRC_1}");
    print!("{__FFIER_SRC_2}");
    print!("{__FFIER_SRC_3}");
    print!("{__FFIER_SRC_4}");
    print!("{__FFIER_SRC_5}");
    print!("{__FFIER_SRC_6}");
    print!("{__FFIER_SRC_7}");
    print!("{__FFIER_SRC_8}");
}
