// Auto-generated by gen-rust-client. Do not edit manually.
// Regenerate with: just gen-rust-client

#[allow(unused_imports)]
use std::os::unix::io::{AsRawFd, BorrowedFd, FromRawFd, OwnedFd};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TestError {
    NotFound,
    CustomMessage,
    InvalidInput,
}
impl TestError {
    pub fn from_ffi(mut err: ffier::FfierError) -> Self {
        let code = err.code;
        unsafe { err.free() };
        match code {
            1u64 => Self::NotFound,
            2u64 => Self::CustomMessage,
            3u64 => Self::InvalidInput,
            other => panic!("unknown {} error code {}", "TestError", other),
        }
    }
}
impl std::fmt::Display for TestError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotFound => write!(f, "not found"),
            Self::CustomMessage => write!(f, "custom error message"),
            Self::InvalidInput => write!(f, "invalid input"),
        }
    }
}
impl std::error::Error for TestError {}
unsafe extern "C" {
    fn ft_widget_destroy(handle: *mut core::ffi::c_void);
    fn ft_widget_new() -> *mut core::ffi::c_void;
    fn ft_widget_with_name(name: ffier::FfierBytes) -> *mut core::ffi::c_void;
    fn ft_widget_get_count(handle: *mut core::ffi::c_void) -> i32;
    fn ft_widget_set_count(handle: *mut core::ffi::c_void, n: i32);
    fn ft_widget_name(handle: *mut core::ffi::c_void) -> ffier::FfierBytes;
    fn ft_widget_data(handle: *mut core::ffi::c_void) -> ffier::FfierBytes;
    fn ft_widget_echo(handle: *mut core::ffi::c_void, s: ffier::FfierBytes) -> ffier::FfierBytes;
    fn ft_widget_is_active(handle: *mut core::ffi::c_void) -> bool;
    fn ft_widget_negate(handle: *mut core::ffi::c_void, v: i64) -> i64;
    fn ft_widget_validate(handle: *mut core::ffi::c_void) -> ffier::FfierError;
    fn ft_widget_parse_count(
        handle: *mut core::ffi::c_void,
        s: ffier::FfierBytes,
        result: *mut i32,
    ) -> ffier::FfierError;
    fn ft_widget_describe(
        handle: *mut core::ffi::c_void,
        code: i32,
        result: *mut ffier::FfierBytes,
    ) -> ffier::FfierError;
    fn ft_widget_fail_always(handle: *mut core::ffi::c_void) -> ffier::FfierError;
    fn ft_widget_fail_with_value(
        handle: *mut core::ffi::c_void,
        result: *mut i32,
    ) -> ffier::FfierError;
    fn ft_widget_set_tags(
        handle: *mut core::ffi::c_void,
        tags: *const ffier::FfierBytes,
        tags_len: usize,
    );
    fn ft_widget_tags_joined(handle: *mut core::ffi::c_void) -> ffier::FfierBytes;
    fn ft_widget_create_gadget(handle: *mut core::ffi::c_void) -> *mut core::ffi::c_void;
    fn ft_widget_try_create_gadget(
        handle: *mut core::ffi::c_void,
        ok: bool,
        result: *mut *mut core::ffi::c_void,
    ) -> ffier::FfierError;
    fn ft_widget_read_gadget(handle: *mut core::ffi::c_void, g: *mut core::ffi::c_void) -> i32;
    fn ft_widget_update_gadget(handle: *mut core::ffi::c_void, g: *mut core::ffi::c_void, v: i32);
    fn ft_widget_consume(handle: *mut core::ffi::c_void);
    fn ft_widget_fd_number(handle: *mut core::ffi::c_void, fd: i32) -> i32;
    fn ft_widget_dup_fd(handle: *mut core::ffi::c_void, fd: i32) -> i32;
}
pub struct Widget(*mut core::ffi::c_void);
impl Widget {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiType for Widget {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &str = "";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Widget {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Widget").field(&self.0).finish()
    }
}
impl Widget {
    #[doc = " Create a new widget with default values."]
    pub fn new() -> Widget {
        let __raw = unsafe { ft_widget_new() };
        <Widget as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Create a widget with a given name."]
    pub fn with_name(name: &str) -> Widget {
        let __raw = unsafe { ft_widget_with_name(ffier::FfierBytes::from_str(name)) };
        <Widget as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Get the current count."]
    pub fn get_count(&self) -> i32 {
        let __raw = unsafe { ft_widget_get_count(self.0) };
        __raw
    }
    #[doc = " Set the count."]
    pub fn set_count(&mut self, n: i32) {
        unsafe { ft_widget_set_count(self.0, n) }
    }
    #[doc = " Get the widget name."]
    pub fn name(&self) -> &str {
        let __raw = unsafe { ft_widget_name(self.0) };
        unsafe {
            core::str::from_utf8_unchecked(core::slice::from_raw_parts(__raw.data, __raw.len))
        }
    }
    #[doc = " Get the raw name bytes."]
    pub fn data(&self) -> &[u8] {
        let __raw = unsafe { ft_widget_data(self.0) };
        unsafe { core::slice::from_raw_parts(__raw.data, __raw.len) }
    }
    #[doc = " Echo back the given string (zero-copy borrow passthrough)."]
    pub fn echo(&self, s: &str) -> &str {
        let __raw = unsafe { ft_widget_echo(self.0, ffier::FfierBytes::from_str(s)) };
        unsafe {
            core::str::from_utf8_unchecked(core::slice::from_raw_parts(__raw.data, __raw.len))
        }
    }
    #[doc = " Check if the widget is active."]
    pub fn is_active(&self) -> bool {
        let __raw = unsafe { ft_widget_is_active(self.0) };
        __raw
    }
    #[doc = " Negate a 64-bit integer."]
    pub fn negate(&self, v: i64) -> i64 {
        let __raw = unsafe { ft_widget_negate(self.0, v) };
        __raw
    }
    #[doc = " Validate internal state (always succeeds for default widget)."]
    pub fn validate(&self) -> Result<(), TestError> {
        let __err = unsafe { ft_widget_validate(self.0) };
        if __err.code == 0 {
            Ok(())
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Parse a count value from the name length, returning error if name matches trigger."]
    pub fn parse_count(&self, s: &str) -> Result<i32, TestError> {
        let mut __out = std::mem::MaybeUninit::uninit();
        let __err = unsafe {
            ft_widget_parse_count(self.0, ffier::FfierBytes::from_str(s), __out.as_mut_ptr())
        };
        if __err.code == 0 {
            Ok(unsafe { __out.assume_init() })
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Describe a code as a string."]
    pub fn describe(&self, code: i32) -> Result<&str, TestError> {
        let mut __out = ffier::FfierBytes::EMPTY;
        let __err = unsafe { ft_widget_describe(self.0, code, &mut __out) };
        if __err.code == 0 {
            Ok(unsafe {
                core::str::from_utf8_unchecked(core::slice::from_raw_parts(__out.data, __out.len))
            })
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Always fails with an error."]
    pub fn fail_always(&self) -> Result<(), TestError> {
        let __err = unsafe { ft_widget_fail_always(self.0) };
        if __err.code == 0 {
            Ok(())
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Always fails with an error (value variant)."]
    pub fn fail_with_value(&self) -> Result<i32, TestError> {
        let mut __out = std::mem::MaybeUninit::uninit();
        let __err = unsafe { ft_widget_fail_with_value(self.0, __out.as_mut_ptr()) };
        if __err.code == 0 {
            Ok(unsafe { __out.assume_init() })
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Set tags from a string slice."]
    pub fn set_tags(&mut self, tags: &[&str]) {
        let __ffi_strs: Vec<ffier::FfierBytes> = tags
            .iter()
            .map(|s| ffier::FfierBytes::from_str(s))
            .collect();
        unsafe { ft_widget_set_tags(self.0, __ffi_strs.as_ptr(), __ffi_strs.len()) }
    }
    #[doc = " Get joined tags."]
    pub fn tags_joined(&self) -> &str {
        let __raw = unsafe { ft_widget_tags_joined(self.0) };
        unsafe {
            core::str::from_utf8_unchecked(core::slice::from_raw_parts(__raw.data, __raw.len))
        }
    }
    #[doc = " Create a new gadget with the widget's count as initial value."]
    pub fn create_gadget(&self) -> Gadget {
        let __raw = unsafe { ft_widget_create_gadget(self.0) };
        <Gadget as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Try to create a gadget; fails if ok is false."]
    pub fn try_create_gadget(&self, ok: bool) -> Result<Gadget, TestError> {
        let mut __out = std::mem::MaybeUninit::uninit();
        let __err = unsafe { ft_widget_try_create_gadget(self.0, ok, __out.as_mut_ptr()) };
        if __err.code == 0 {
            Ok(<Gadget as ffier::FfiType>::from_c(unsafe {
                __out.assume_init()
            }))
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Read a gadget's value."]
    pub fn read_gadget(&self, g: &Gadget) -> i32 {
        let __raw = unsafe { ft_widget_read_gadget(self.0, g.0) };
        __raw
    }
    #[doc = " Update a gadget's value."]
    pub fn update_gadget(&self, g: &mut Gadget, v: i32) {
        unsafe { ft_widget_update_gadget(self.0, g.0, v) }
    }
    #[doc = " Consume the widget (by-value self, void return)."]
    pub fn consume(self) {
        let __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        unsafe { ft_widget_consume(__handle) }
    }
    #[doc = " Get the raw fd number from a borrowed fd."]
    pub fn fd_number(&self, fd: BorrowedFd<'_>) -> i32 {
        let __raw =
            unsafe { ft_widget_fd_number(self.0, <BorrowedFd<'_> as ffier::FfiType>::into_c(fd)) };
        __raw
    }
    #[doc = " Duplicate a file descriptor (returns owned fd)."]
    pub fn dup_fd(&self, fd: BorrowedFd<'_>) -> OwnedFd {
        let __raw =
            unsafe { ft_widget_dup_fd(self.0, <BorrowedFd<'_> as ffier::FfiType>::into_c(fd)) };
        <OwnedFd as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Widget {
    fn drop(&mut self) {
        unsafe { ft_widget_destroy(self.0) }
    }
}
unsafe extern "C" {
    fn ft_gadget_destroy(handle: *mut core::ffi::c_void);
    fn ft_gadget_get(handle: *mut core::ffi::c_void) -> i32;
}
pub struct Gadget(*mut core::ffi::c_void);
impl Gadget {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiType for Gadget {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &str = "";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Gadget {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Gadget").field(&self.0).finish()
    }
}
impl Gadget {
    #[doc = " Get the gadget value."]
    pub fn get(&self) -> i32 {
        let __raw = unsafe { ft_gadget_get(self.0) };
        __raw
    }
}
impl Drop for Gadget {
    fn drop(&mut self) {
        unsafe { ft_gadget_destroy(self.0) }
    }
}
unsafe extern "C" {
    fn ft_config_destroy(handle: *mut core::ffi::c_void);
    fn ft_config_new() -> *mut core::ffi::c_void;
    fn ft_config_set_name(handle: *mut *mut core::ffi::c_void, name: ffier::FfierBytes);
    fn ft_config_set_size(handle: *mut *mut core::ffi::c_void, size: i32);
    fn ft_config_validated(handle: *mut *mut core::ffi::c_void) -> ffier::FfierError;
    fn ft_config_get_name(handle: *mut core::ffi::c_void) -> ffier::FfierBytes;
    fn ft_config_get_size(handle: *mut core::ffi::c_void) -> i32;
}
pub struct Config(*mut core::ffi::c_void);
impl Config {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiType for Config {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &str = "";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Config {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Config").field(&self.0).finish()
    }
}
impl Config {
    #[doc = " Create a new config."]
    pub fn new() -> Config {
        let __raw = unsafe { ft_config_new() };
        <Config as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Set the name (builder pattern: consumes self, returns Self)."]
    pub fn set_name(self, name: &str) -> Self {
        let mut __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        unsafe { ft_config_set_name(&mut __handle, ffier::FfierBytes::from_str(name)) };
        Self(__handle)
    }
    #[doc = " Set the size (builder pattern)."]
    pub fn set_size(self, size: i32) -> Self {
        let mut __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        unsafe { ft_config_set_size(&mut __handle, size) };
        Self(__handle)
    }
    #[doc = " Validate and return self, or error if name is empty."]
    pub fn validated(self) -> Result<Self, TestError> {
        let mut __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        let __err = unsafe { ft_config_validated(&mut __handle) };
        if __err.code == 0 {
            Ok(Self(__handle))
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Get the config name."]
    pub fn get_name(&self) -> &str {
        let __raw = unsafe { ft_config_get_name(self.0) };
        unsafe {
            core::str::from_utf8_unchecked(core::slice::from_raw_parts(__raw.data, __raw.len))
        }
    }
    #[doc = " Get the config size."]
    pub fn get_size(&self) -> i32 {
        let __raw = unsafe { ft_config_get_size(self.0) };
        __raw
    }
}
impl Drop for Config {
    fn drop(&mut self) {
        unsafe { ft_config_destroy(self.0) }
    }
}
unsafe extern "C" {
    fn ft_gizmo_destroy(handle: *mut core::ffi::c_void);
    fn ft_gizmo_name(handle: *mut core::ffi::c_void) -> ffier::FfierBytes;
    fn ft_gizmo_size(handle: *mut core::ffi::c_void) -> i32;
}
pub struct Gizmo(*mut core::ffi::c_void);
impl Gizmo {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiType for Gizmo {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &str = "";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Gizmo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Gizmo").field(&self.0).finish()
    }
}
impl Gizmo {
    #[doc = " Get the gizmo name."]
    pub fn name(&self) -> &str {
        let __raw = unsafe { ft_gizmo_name(self.0) };
        unsafe {
            core::str::from_utf8_unchecked(core::slice::from_raw_parts(__raw.data, __raw.len))
        }
    }
    #[doc = " Get the gizmo size."]
    pub fn size(&self) -> i32 {
        let __raw = unsafe { ft_gizmo_size(self.0) };
        __raw
    }
}
impl Drop for Gizmo {
    fn drop(&mut self) {
        unsafe { ft_gizmo_destroy(self.0) }
    }
}
unsafe extern "C" {
    fn ft_gizmo_builder_destroy(handle: *mut core::ffi::c_void);
    fn ft_gizmo_builder_new() -> *mut core::ffi::c_void;
    fn ft_gizmo_builder_set_name(handle: *mut core::ffi::c_void, name: ffier::FfierBytes);
    fn ft_gizmo_builder_set_size(handle: *mut core::ffi::c_void, size: i32);
    fn ft_gizmo_builder_build(handle: *mut core::ffi::c_void) -> *mut core::ffi::c_void;
    fn ft_gizmo_builder_try_build(
        handle: *mut core::ffi::c_void,
        result: *mut *mut core::ffi::c_void,
    ) -> ffier::FfierError;
}
pub struct GizmoBuilder(*mut core::ffi::c_void);
impl GizmoBuilder {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiType for GizmoBuilder {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &str = "";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for GizmoBuilder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("GizmoBuilder").field(&self.0).finish()
    }
}
impl GizmoBuilder {
    #[doc = " Create a new gizmo builder."]
    pub fn new() -> GizmoBuilder {
        let __raw = unsafe { ft_gizmo_builder_new() };
        <GizmoBuilder as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Set the gizmo name."]
    pub fn set_name(&mut self, name: &str) {
        unsafe { ft_gizmo_builder_set_name(self.0, ffier::FfierBytes::from_str(name)) }
    }
    #[doc = " Set the gizmo size."]
    pub fn set_size(&mut self, size: i32) {
        unsafe { ft_gizmo_builder_set_size(self.0, size) }
    }
    #[doc = " Build the gizmo (consumes builder, returns different type)."]
    pub fn build(self) -> Gizmo {
        let __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        let __raw = unsafe { ft_gizmo_builder_build(__handle) };
        <Gizmo as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Try to build the gizmo; fails if name is empty."]
    pub fn try_build(self) -> Result<Gizmo, TestError> {
        let __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        let mut __out = std::mem::MaybeUninit::uninit();
        let __err = unsafe { ft_gizmo_builder_try_build(__handle, __out.as_mut_ptr()) };
        if __err.code == 0 {
            Ok(<Gizmo as ffier::FfiType>::from_c(unsafe {
                __out.assume_init()
            }))
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
}
impl Drop for GizmoBuilder {
    fn drop(&mut self) {
        unsafe { ft_gizmo_builder_destroy(self.0) }
    }
}
unsafe extern "C" {
    fn ft_view_destroy(handle: *mut core::ffi::c_void);
    fn ft_view_create(source: *mut core::ffi::c_void) -> *mut core::ffi::c_void;
    fn ft_view_source_count(handle: *mut core::ffi::c_void) -> i32;
    fn ft_view_set_label(handle: *mut core::ffi::c_void, label: ffier::FfierBytes);
    fn ft_view_label(handle: *mut core::ffi::c_void) -> ffier::FfierBytes;
}
pub struct View<'a>(*mut core::ffi::c_void, std::marker::PhantomData<&'a ()>);
impl<'a> View<'a> {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr, std::marker::PhantomData)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl<'a> std::fmt::Debug for View<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("View").field(&self.0).finish()
    }
}
impl<'a> View<'a> {
    #[doc = " Create a view that borrows a widget."]
    pub fn create(source: &Widget) -> View<'_> {
        let __raw = unsafe { ft_view_create(source.0) };
        <View<'_>>::__from_raw(__raw)
    }
    #[doc = " Read the source widget's count through the borrow."]
    pub fn source_count(&self) -> i32 {
        let __raw = unsafe { ft_view_source_count(self.0) };
        __raw
    }
    #[doc = " Set the view label."]
    pub fn set_label(&mut self, label: &str) {
        unsafe { ft_view_set_label(self.0, ffier::FfierBytes::from_str(label)) }
    }
    #[doc = " Get the view label."]
    pub fn label(&self) -> &str {
        let __raw = unsafe { ft_view_label(self.0) };
        unsafe {
            core::str::from_utf8_unchecked(core::slice::from_raw_parts(__raw.data, __raw.len))
        }
    }
}
impl<'a> Drop for View<'a> {
    fn drop(&mut self) {
        unsafe { ft_view_destroy(self.0) }
    }
}
unsafe extern "C" {
    fn ft_pipeline_destroy(handle: *mut core::ffi::c_void);
    fn ft_pipeline_new() -> *mut core::ffi::c_void;
    fn ft_pipeline_run(handle: *mut core::ffi::c_void, proc: *mut core::ffi::c_void, input: i32);
    fn ft_pipeline_result_count(handle: *mut core::ffi::c_void) -> i32;
    fn ft_pipeline_last_result(
        handle: *mut core::ffi::c_void,
        result: *mut i32,
    ) -> ffier::FfierError;
}
pub struct Pipeline(*mut core::ffi::c_void);
impl Pipeline {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiType for Pipeline {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &str = "";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Pipeline {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Pipeline").field(&self.0).finish()
    }
}
impl Pipeline {
    #[doc = " Create a new pipeline."]
    pub fn new() -> Pipeline {
        let __raw = unsafe { ft_pipeline_new() };
        <Pipeline as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Run a processor on the given input."]
    pub fn run(&mut self, proc: impl IntoProcessorHandle, input: i32) {
        unsafe { ft_pipeline_run(self.0, proc.into_raw_handle(), input) }
    }
    #[doc = " Get the number of results."]
    pub fn result_count(&self) -> i32 {
        let __raw = unsafe { ft_pipeline_result_count(self.0) };
        __raw
    }
    #[doc = " Get the last result, or error if empty."]
    pub fn last_result(&self) -> Result<i32, TestError> {
        let mut __out = std::mem::MaybeUninit::uninit();
        let __err = unsafe { ft_pipeline_last_result(self.0, __out.as_mut_ptr()) };
        if __err.code == 0 {
            Ok(unsafe { __out.assume_init() })
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
}
impl Drop for Pipeline {
    fn drop(&mut self) {
        unsafe { ft_pipeline_destroy(self.0) }
    }
}
pub trait IntoProcessorHandle {
    fn into_raw_handle(self) -> *mut core::ffi::c_void;
}
impl IntoProcessorHandle for VtableProcessor {
    fn into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
#[repr(C)]
pub struct ProcessorVtable {
    pub process: unsafe extern "C" fn(*mut core::ffi::c_void, i32) -> i32,
    pub name: unsafe extern "C" fn(*mut core::ffi::c_void) -> ffier::FfierBytes,
    pub on_notify: unsafe extern "C" fn(*mut core::ffi::c_void, i32),
    pub drop: Option<unsafe extern "C" fn(*mut core::ffi::c_void)>,
}
unsafe extern "C" {
    fn ft_processor_from_vtable(
        user_data: *mut core::ffi::c_void,
        vtable: *const ProcessorVtable,
    ) -> *mut core::ffi::c_void;
}
pub struct VtableProcessor(*mut core::ffi::c_void);
impl VtableProcessor {
    pub fn new(user_data: *mut core::ffi::c_void, vtable: &ProcessorVtable) -> Self {
        Self(unsafe { ft_processor_from_vtable(user_data, vtable) })
    }
}
impl Drop for VtableProcessor {
    fn drop(&mut self) {}
}
