// Auto-generated by gen-rust-client. Do not edit manually.
// Regenerate with: just gen-rust-client

#[allow(unused_imports)]
use std::os::unix::io::{AsRawFd, BorrowedFd, FromRawFd, OwnedFd};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TestError {
    NotFound,
    CustomMessage,
    InvalidInput,
}
impl TestError {
    pub fn from_ffi(mut err: ffier::FfierError) -> Self {
        let code = err.code;
        unsafe { err.free() };
        match code {
            1u64 => Self::NotFound,
            2u64 => Self::CustomMessage,
            3u64 => Self::InvalidInput,
            other => panic!("unknown {} error code {}", "TestError", other),
        }
    }
}
impl std::fmt::Display for TestError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::NotFound => write!(f, "not found"),
            Self::CustomMessage => write!(f, "custom error message"),
            Self::InvalidInput => write!(f, "invalid input"),
        }
    }
}
impl std::error::Error for TestError {}
unsafe extern "C" {
    pub fn ft_widget_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_widget_new() -> <Widget as ffier::FfiType>::CRepr;
    pub fn ft_widget_with_name(
        name: <&'static str as ffier::FfiType>::CRepr,
    ) -> <Widget as ffier::FfiType>::CRepr;
    pub fn ft_widget_get_count(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
    pub fn ft_widget_set_count(handle: *mut core::ffi::c_void, n: <i32 as ffier::FfiType>::CRepr);
    pub fn ft_widget_name(
        handle: *mut core::ffi::c_void,
    ) -> <&'static str as ffier::FfiType>::CRepr;
    pub fn ft_widget_data(
        handle: *mut core::ffi::c_void,
    ) -> <&'static [u8] as ffier::FfiType>::CRepr;
    pub fn ft_widget_sum_bytes(
        handle: *mut core::ffi::c_void,
        data: <&'static [u8] as ffier::FfiType>::CRepr,
    ) -> <i32 as ffier::FfiType>::CRepr;
    pub fn ft_widget_echo(
        handle: *mut core::ffi::c_void,
        s: <&'static str as ffier::FfiType>::CRepr,
    ) -> <&'static str as ffier::FfiType>::CRepr;
    pub fn ft_widget_is_active(handle: *mut core::ffi::c_void) -> <bool as ffier::FfiType>::CRepr;
    pub fn ft_widget_negate(
        handle: *mut core::ffi::c_void,
        v: <i64 as ffier::FfiType>::CRepr,
    ) -> <i64 as ffier::FfiType>::CRepr;
    pub fn ft_widget_validate(handle: *mut core::ffi::c_void) -> ffier::FfierError;
    pub fn ft_widget_parse_count(
        handle: *mut core::ffi::c_void,
        s: <&'static str as ffier::FfiType>::CRepr,
        result: *mut <i32 as ffier::FfiType>::CRepr,
    ) -> ffier::FfierError;
    pub fn ft_widget_describe(
        handle: *mut core::ffi::c_void,
        code: <i32 as ffier::FfiType>::CRepr,
        result: *mut <&'static str as ffier::FfiType>::CRepr,
    ) -> ffier::FfierError;
    pub fn ft_widget_fail_always(handle: *mut core::ffi::c_void) -> ffier::FfierError;
    pub fn ft_widget_fail_with_value(
        handle: *mut core::ffi::c_void,
        result: *mut <i32 as ffier::FfiType>::CRepr,
    ) -> ffier::FfierError;
    pub fn ft_widget_set_tags(
        handle: *mut core::ffi::c_void,
        tags: *const ffier::FfierBytes,
        tags_len: usize,
    );
    pub fn ft_widget_tags_joined(
        handle: *mut core::ffi::c_void,
    ) -> <&'static str as ffier::FfiType>::CRepr;
    pub fn ft_widget_create_gadget(
        handle: *mut core::ffi::c_void,
    ) -> <Gadget as ffier::FfiType>::CRepr;
    pub fn ft_widget_try_create_gadget(
        handle: *mut core::ffi::c_void,
        ok: <bool as ffier::FfiType>::CRepr,
        result: *mut <Gadget as ffier::FfiType>::CRepr,
    ) -> ffier::FfierError;
    pub fn ft_widget_read_gadget(
        handle: *mut core::ffi::c_void,
        g: <&'static Gadget as ffier::FfiType>::CRepr,
    ) -> <i32 as ffier::FfiType>::CRepr;
    pub fn ft_widget_update_gadget(
        handle: *mut core::ffi::c_void,
        g: <&'static mut Gadget as ffier::FfiType>::CRepr,
        v: <i32 as ffier::FfiType>::CRepr,
    );
    pub fn ft_widget_consume(handle: *mut core::ffi::c_void);
    pub fn ft_widget_fd_number(
        handle: *mut core::ffi::c_void,
        fd: <BorrowedFd<'static> as ffier::FfiType>::CRepr,
    ) -> <i32 as ffier::FfiType>::CRepr;
    pub fn ft_widget_dup_fd(
        handle: *mut core::ffi::c_void,
        fd: <BorrowedFd<'static> as ffier::FfiType>::CRepr,
    ) -> <OwnedFd as ffier::FfiType>::CRepr;
}
pub struct Widget(*mut core::ffi::c_void);
impl Widget {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Widget {
    const C_HANDLE_NAME: &'static str = "Widget";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Widget {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Widget";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Widget {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Widget").field(&self.0).finish()
    }
}
impl Widget {
    #[doc = " Create a new widget with default values."]
    pub fn new() -> Widget {
        let __raw = unsafe { ft_widget_new() };
        <Widget as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Create a widget with a given name."]
    pub fn with_name(name: &str) -> Widget {
        let __raw = unsafe { ft_widget_with_name(<&str as ffier::FfiType>::into_c(name)) };
        <Widget as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Get the current count."]
    pub fn get_count(&self) -> i32 {
        let __raw = unsafe { ft_widget_get_count(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Set the count."]
    pub fn set_count(&mut self, n: i32) {
        unsafe { ft_widget_set_count(self.0, <i32 as ffier::FfiType>::into_c(n)) }
    }
    #[doc = " Get the widget name."]
    pub fn name(&self) -> &str {
        let __raw = unsafe { ft_widget_name(self.0) };
        <&str as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Get the raw name bytes."]
    pub fn data(&self) -> &[u8] {
        let __raw = unsafe { ft_widget_data(self.0) };
        <&[u8] as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Sum the bytes of a byte slice."]
    pub fn sum_bytes(&self, data: &[u8]) -> i32 {
        let __raw = unsafe { ft_widget_sum_bytes(self.0, <&[u8] as ffier::FfiType>::into_c(data)) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Echo back the given string (zero-copy borrow passthrough)."]
    pub fn echo<'a>(&self, s: &'a str) -> &'a str {
        let __raw = unsafe { ft_widget_echo(self.0, <&'a str as ffier::FfiType>::into_c(s)) };
        <&'a str as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Check if the widget is active."]
    pub fn is_active(&self) -> bool {
        let __raw = unsafe { ft_widget_is_active(self.0) };
        <bool as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Negate a 64-bit integer."]
    pub fn negate(&self, v: i64) -> i64 {
        let __raw = unsafe { ft_widget_negate(self.0, <i64 as ffier::FfiType>::into_c(v)) };
        <i64 as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Validate internal state (always succeeds for default widget)."]
    pub fn validate(&self) -> Result<(), TestError> {
        let __err = unsafe { ft_widget_validate(self.0) };
        if __err.code == 0 {
            Ok(())
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Parse a count value from the name length, returning error if name matches trigger."]
    pub fn parse_count(&self, s: &str) -> Result<i32, TestError> {
        let mut __out = std::mem::MaybeUninit::uninit();
        let __err = unsafe {
            ft_widget_parse_count(
                self.0,
                <&str as ffier::FfiType>::into_c(s),
                __out.as_mut_ptr(),
            )
        };
        if __err.code == 0 {
            Ok(<i32 as ffier::FfiType>::from_c(unsafe {
                __out.assume_init()
            }))
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Describe a code as a string."]
    pub fn describe(&self, code: i32) -> Result<&str, TestError> {
        let mut __out = std::mem::MaybeUninit::uninit();
        let __err = unsafe {
            ft_widget_describe(
                self.0,
                <i32 as ffier::FfiType>::into_c(code),
                __out.as_mut_ptr(),
            )
        };
        if __err.code == 0 {
            Ok(<&str as ffier::FfiType>::from_c(unsafe {
                __out.assume_init()
            }))
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Always fails with an error."]
    pub fn fail_always(&self) -> Result<(), TestError> {
        let __err = unsafe { ft_widget_fail_always(self.0) };
        if __err.code == 0 {
            Ok(())
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Always fails with an error (value variant)."]
    pub fn fail_with_value(&self) -> Result<i32, TestError> {
        let mut __out = std::mem::MaybeUninit::uninit();
        let __err = unsafe { ft_widget_fail_with_value(self.0, __out.as_mut_ptr()) };
        if __err.code == 0 {
            Ok(<i32 as ffier::FfiType>::from_c(unsafe {
                __out.assume_init()
            }))
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Set tags from a string slice."]
    pub fn set_tags(&mut self, tags: &[&str]) {
        let __ffi_strs: Vec<ffier::FfierBytes> = tags
            .iter()
            .map(|s| unsafe { ffier::FfierBytes::from_str(s) })
            .collect();
        unsafe { ft_widget_set_tags(self.0, __ffi_strs.as_ptr(), __ffi_strs.len()) }
    }
    #[doc = " Get joined tags."]
    pub fn tags_joined(&self) -> &str {
        let __raw = unsafe { ft_widget_tags_joined(self.0) };
        <&str as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Create a new gadget with the widget's count as initial value."]
    pub fn create_gadget(&self) -> Gadget {
        let __raw = unsafe { ft_widget_create_gadget(self.0) };
        <Gadget as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Try to create a gadget; fails if ok is false."]
    pub fn try_create_gadget(&self, ok: bool) -> Result<Gadget, TestError> {
        let mut __out = std::mem::MaybeUninit::uninit();
        let __err = unsafe {
            ft_widget_try_create_gadget(
                self.0,
                <bool as ffier::FfiType>::into_c(ok),
                __out.as_mut_ptr(),
            )
        };
        if __err.code == 0 {
            Ok(<Gadget as ffier::FfiType>::from_c(unsafe {
                __out.assume_init()
            }))
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Read a gadget's value."]
    pub fn read_gadget(&self, g: &Gadget) -> i32 {
        let __raw =
            unsafe { ft_widget_read_gadget(self.0, <&Gadget as ffier::FfiType>::into_c(g)) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Update a gadget's value."]
    pub fn update_gadget(&self, g: &mut Gadget, v: i32) {
        unsafe {
            ft_widget_update_gadget(
                self.0,
                <&mut Gadget as ffier::FfiType>::into_c(g),
                <i32 as ffier::FfiType>::into_c(v),
            )
        }
    }
    #[doc = " Consume the widget (by-value self, void return)."]
    pub fn consume(self) {
        let __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        unsafe { ft_widget_consume(__handle) }
    }
    #[doc = " Get the raw fd number from a borrowed fd."]
    pub fn fd_number(&self, fd: BorrowedFd<'_>) -> i32 {
        let __raw =
            unsafe { ft_widget_fd_number(self.0, <BorrowedFd<'_> as ffier::FfiType>::into_c(fd)) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Duplicate a file descriptor (returns owned fd)."]
    pub fn dup_fd(&self, fd: BorrowedFd<'_>) -> OwnedFd {
        let __raw =
            unsafe { ft_widget_dup_fd(self.0, <BorrowedFd<'_> as ffier::FfiType>::into_c(fd)) };
        <OwnedFd as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Widget {
    fn drop(&mut self) {
        unsafe { ft_widget_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_gadget_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_gadget_get(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
}
pub struct Gadget(*mut core::ffi::c_void);
impl Gadget {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Gadget {
    const C_HANDLE_NAME: &'static str = "Gadget";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Gadget {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Gadget";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Gadget {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Gadget").field(&self.0).finish()
    }
}
impl Gadget {
    #[doc = " Get the gadget value."]
    pub fn get(&self) -> i32 {
        let __raw = unsafe { ft_gadget_get(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Gadget {
    fn drop(&mut self) {
        unsafe { ft_gadget_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_config_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_config_new() -> <Config as ffier::FfiType>::CRepr;
    pub fn ft_config_set_name(
        handle: *mut *mut core::ffi::c_void,
        name: <&'static str as ffier::FfiType>::CRepr,
    );
    pub fn ft_config_set_size(
        handle: *mut *mut core::ffi::c_void,
        size: <i32 as ffier::FfiType>::CRepr,
    );
    pub fn ft_config_validated(handle: *mut *mut core::ffi::c_void) -> ffier::FfierError;
    pub fn ft_config_get_name(
        handle: *mut core::ffi::c_void,
    ) -> <&'static str as ffier::FfiType>::CRepr;
    pub fn ft_config_get_size(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
}
pub struct Config(*mut core::ffi::c_void);
impl Config {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Config {
    const C_HANDLE_NAME: &'static str = "Config";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Config {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Config";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Config {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Config").field(&self.0).finish()
    }
}
impl Config {
    #[doc = " Create a new config."]
    pub fn new() -> Config {
        let __raw = unsafe { ft_config_new() };
        <Config as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Set the name (builder pattern: consumes self, returns Self)."]
    pub fn set_name(self, name: &str) -> Self {
        let mut __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        unsafe { ft_config_set_name(&mut __handle, <&str as ffier::FfiType>::into_c(name)) };
        Self(__handle)
    }
    #[doc = " Set the size (builder pattern)."]
    pub fn set_size(self, size: i32) -> Self {
        let mut __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        unsafe { ft_config_set_size(&mut __handle, <i32 as ffier::FfiType>::into_c(size)) };
        Self(__handle)
    }
    #[doc = " Validate and return self, or error if name is empty."]
    pub fn validated(self) -> Result<Self, TestError> {
        let mut __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        let __err = unsafe { ft_config_validated(&mut __handle) };
        if __err.code == 0 {
            Ok(Self(__handle))
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
    #[doc = " Get the config name."]
    pub fn get_name(&self) -> &str {
        let __raw = unsafe { ft_config_get_name(self.0) };
        <&str as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Get the config size."]
    pub fn get_size(&self) -> i32 {
        let __raw = unsafe { ft_config_get_size(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Config {
    fn drop(&mut self) {
        unsafe { ft_config_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_gizmo_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_gizmo_name(handle: *mut core::ffi::c_void)
        -> <&'static str as ffier::FfiType>::CRepr;
    pub fn ft_gizmo_size(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
}
pub struct Gizmo(*mut core::ffi::c_void);
impl Gizmo {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Gizmo {
    const C_HANDLE_NAME: &'static str = "Gizmo";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Gizmo {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Gizmo";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Gizmo {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Gizmo").field(&self.0).finish()
    }
}
impl Gizmo {
    #[doc = " Get the gizmo name."]
    pub fn name(&self) -> &str {
        let __raw = unsafe { ft_gizmo_name(self.0) };
        <&str as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Get the gizmo size."]
    pub fn size(&self) -> i32 {
        let __raw = unsafe { ft_gizmo_size(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Gizmo {
    fn drop(&mut self) {
        unsafe { ft_gizmo_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_gizmo_builder_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_gizmo_builder_new() -> <GizmoBuilder as ffier::FfiType>::CRepr;
    pub fn ft_gizmo_builder_set_name(
        handle: *mut core::ffi::c_void,
        name: <&'static str as ffier::FfiType>::CRepr,
    );
    pub fn ft_gizmo_builder_set_size(
        handle: *mut core::ffi::c_void,
        size: <i32 as ffier::FfiType>::CRepr,
    );
    pub fn ft_gizmo_builder_build(
        handle: *mut core::ffi::c_void,
    ) -> <Gizmo as ffier::FfiType>::CRepr;
    pub fn ft_gizmo_builder_try_build(
        handle: *mut core::ffi::c_void,
        result: *mut <Gizmo as ffier::FfiType>::CRepr,
    ) -> ffier::FfierError;
}
pub struct GizmoBuilder(*mut core::ffi::c_void);
impl GizmoBuilder {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for GizmoBuilder {
    const C_HANDLE_NAME: &'static str = "GizmoBuilder";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for GizmoBuilder {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "GizmoBuilder";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for GizmoBuilder {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("GizmoBuilder").field(&self.0).finish()
    }
}
impl GizmoBuilder {
    #[doc = " Create a new gizmo builder."]
    pub fn new() -> GizmoBuilder {
        let __raw = unsafe { ft_gizmo_builder_new() };
        <GizmoBuilder as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Set the gizmo name."]
    pub fn set_name(&mut self, name: &str) {
        unsafe { ft_gizmo_builder_set_name(self.0, <&str as ffier::FfiType>::into_c(name)) }
    }
    #[doc = " Set the gizmo size."]
    pub fn set_size(&mut self, size: i32) {
        unsafe { ft_gizmo_builder_set_size(self.0, <i32 as ffier::FfiType>::into_c(size)) }
    }
    #[doc = " Build the gizmo (consumes builder, returns different type)."]
    pub fn build(self) -> Gizmo {
        let __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        let __raw = unsafe { ft_gizmo_builder_build(__handle) };
        <Gizmo as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Try to build the gizmo; fails if name is empty."]
    pub fn try_build(self) -> Result<Gizmo, TestError> {
        let __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        let mut __out = std::mem::MaybeUninit::uninit();
        let __err = unsafe { ft_gizmo_builder_try_build(__handle, __out.as_mut_ptr()) };
        if __err.code == 0 {
            Ok(<Gizmo as ffier::FfiType>::from_c(unsafe {
                __out.assume_init()
            }))
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
}
impl Drop for GizmoBuilder {
    fn drop(&mut self) {
        unsafe { ft_gizmo_builder_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_view_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_view_create(
        source: <&'static Widget as ffier::FfiType>::CRepr,
    ) -> <View<'static> as ffier::FfiType>::CRepr;
    pub fn ft_view_create_labeled(
        source: <&'static Widget as ffier::FfiType>::CRepr,
        label: <&'static str as ffier::FfiType>::CRepr,
    ) -> <View<'static> as ffier::FfiType>::CRepr;
    pub fn ft_view_source_count(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
    pub fn ft_view_set_label(
        handle: *mut core::ffi::c_void,
        label: <&'static str as ffier::FfiType>::CRepr,
    );
    pub fn ft_view_label(handle: *mut core::ffi::c_void)
        -> <&'static str as ffier::FfiType>::CRepr;
    pub fn ft_view_copy_label(handle: *mut core::ffi::c_void, other: *mut core::ffi::c_void);
}
pub struct View<'a>(*mut core::ffi::c_void, std::marker::PhantomData<(&'a ())>);
impl<'a> View<'a> {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr, std::marker::PhantomData)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl<'a> ffier::FfiHandle for View<'a> {
    const C_HANDLE_NAME: &'static str = "View";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl<'a> ffier::FfiType for View<'a> {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "View";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl<'a> std::fmt::Debug for View<'a> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("View").field(&self.0).finish()
    }
}
impl<'a> View<'a> {
    #[doc = " Create a view that borrows a widget."]
    pub fn create(source: &'a Widget) -> View<'a> {
        let __raw = unsafe { ft_view_create(<&'a Widget as ffier::FfiType>::into_c(source)) };
        <View<'a> as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Create a view with a custom label."]
    #[doc = ""]
    #[doc = " Takes two reference params so lifetime elision can't resolve `'_`"]
    #[doc = " in the return type — the struct lifetime must be preserved explicitly."]
    pub fn create_labeled(source: &'a Widget, label: &str) -> View<'a> {
        let __raw = unsafe {
            ft_view_create_labeled(
                <&'a Widget as ffier::FfiType>::into_c(source),
                <&str as ffier::FfiType>::into_c(label),
            )
        };
        <View<'a> as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Read the source widget's count through the borrow."]
    pub fn source_count(&self) -> i32 {
        let __raw = unsafe { ft_view_source_count(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Set the view label."]
    pub fn set_label(&mut self, label: &str) {
        unsafe { ft_view_set_label(self.0, <&str as ffier::FfiType>::into_c(label)) }
    }
    #[doc = " Get the view label."]
    pub fn label(&self) -> &str {
        let __raw = unsafe { ft_view_label(self.0) };
        <&str as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Copy label from another snapshot (tests impl Trait auto-dispatch)."]
    pub fn copy_label(&mut self, other: impl Snapshot<'a>) {
        unsafe { ft_view_copy_label(self.0, other.__into_raw_handle()) }
    }
}
impl<'a> Drop for View<'a> {
    fn drop(&mut self) {
        unsafe { ft_view_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_view_factory_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_view_factory_new() -> <ViewFactory as ffier::FfiType>::CRepr;
    pub fn ft_view_factory_create_view(
        source: <&'static Widget as ffier::FfiType>::CRepr,
        label: <&'static str as ffier::FfiType>::CRepr,
    ) -> <View<'static> as ffier::FfiType>::CRepr;
}
pub struct ViewFactory(*mut core::ffi::c_void);
impl ViewFactory {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for ViewFactory {
    const C_HANDLE_NAME: &'static str = "ViewFactory";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for ViewFactory {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "ViewFactory";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for ViewFactory {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("ViewFactory").field(&self.0).finish()
    }
}
impl ViewFactory {
    pub fn new() -> ViewFactory {
        let __raw = unsafe { ft_view_factory_new() };
        <ViewFactory as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Create a view from a source widget with a label."]
    #[doc = ""]
    #[doc = " Multiple reference params + lifetime-parameterized return type forces"]
    #[doc = " the generator to introduce a method-level lifetime (can't elide)."]
    pub fn create_view<'a>(source: &'a Widget, label: &str) -> View<'a> {
        let __raw = unsafe {
            ft_view_factory_create_view(
                <&'a Widget as ffier::FfiType>::into_c(source),
                <&str as ffier::FfiType>::into_c(label),
            )
        };
        <View<'a> as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for ViewFactory {
    fn drop(&mut self) {
        unsafe { ft_view_factory_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_pipeline_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_pipeline_new() -> <Pipeline as ffier::FfiType>::CRepr;
    pub fn ft_pipeline_run(
        handle: *mut core::ffi::c_void,
        proc: *mut core::ffi::c_void,
        input: <i32 as ffier::FfiType>::CRepr,
    );
    pub fn ft_pipeline_result_count(
        handle: *mut core::ffi::c_void,
    ) -> <i32 as ffier::FfiType>::CRepr;
    pub fn ft_pipeline_last_result(
        handle: *mut core::ffi::c_void,
        result: *mut <i32 as ffier::FfiType>::CRepr,
    ) -> ffier::FfierError;
}
pub struct Pipeline(*mut core::ffi::c_void);
impl Pipeline {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Pipeline {
    const C_HANDLE_NAME: &'static str = "Pipeline";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Pipeline {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Pipeline";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Pipeline {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Pipeline").field(&self.0).finish()
    }
}
impl Pipeline {
    #[doc = " Create a new pipeline."]
    pub fn new() -> Pipeline {
        let __raw = unsafe { ft_pipeline_new() };
        <Pipeline as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Run a processor on the given input."]
    pub fn run(&mut self, proc: impl Processor, input: i32) {
        unsafe {
            ft_pipeline_run(
                self.0,
                proc.__into_raw_handle(),
                <i32 as ffier::FfiType>::into_c(input),
            )
        }
    }
    #[doc = " Get the number of results."]
    pub fn result_count(&self) -> i32 {
        let __raw = unsafe { ft_pipeline_result_count(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Get the last result, or error if empty."]
    pub fn last_result(&self) -> Result<i32, TestError> {
        let mut __out = std::mem::MaybeUninit::uninit();
        let __err = unsafe { ft_pipeline_last_result(self.0, __out.as_mut_ptr()) };
        if __err.code == 0 {
            Ok(<i32 as ffier::FfiType>::from_c(unsafe {
                __out.assume_init()
            }))
        } else {
            Err(TestError::from_ffi(__err))
        }
    }
}
impl Drop for Pipeline {
    fn drop(&mut self) {
        unsafe { ft_pipeline_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_apple_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_apple_new(weight: <i32 as ffier::FfiType>::CRepr)
        -> <Apple as ffier::FfiType>::CRepr;
}
pub struct Apple(*mut core::ffi::c_void);
impl Apple {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Apple {
    const C_HANDLE_NAME: &'static str = "Apple";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Apple {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Apple";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Apple {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Apple").field(&self.0).finish()
    }
}
impl Apple {
    pub fn new(weight: i32) -> Apple {
        let __raw = unsafe { ft_apple_new(<i32 as ffier::FfiType>::into_c(weight)) };
        <Apple as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Apple {
    fn drop(&mut self) {
        unsafe { ft_apple_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_orange_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_orange_new(
        juice: <i32 as ffier::FfiType>::CRepr,
    ) -> <Orange as ffier::FfiType>::CRepr;
}
pub struct Orange(*mut core::ffi::c_void);
impl Orange {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Orange {
    const C_HANDLE_NAME: &'static str = "Orange";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Orange {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Orange";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Orange {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Orange").field(&self.0).finish()
    }
}
impl Orange {
    pub fn new(juice: i32) -> Orange {
        let __raw = unsafe { ft_orange_new(<i32 as ffier::FfiType>::into_c(juice)) };
        <Orange as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Orange {
    fn drop(&mut self) {
        unsafe { ft_orange_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_banana_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_banana_new(v: <i32 as ffier::FfiType>::CRepr) -> <Banana as ffier::FfiType>::CRepr;
}
pub struct Banana(*mut core::ffi::c_void);
impl Banana {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Banana {
    const C_HANDLE_NAME: &'static str = "Banana";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Banana {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Banana";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Banana {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Banana").field(&self.0).finish()
    }
}
impl Banana {
    pub fn new(v: i32) -> Banana {
        let __raw = unsafe { ft_banana_new(<i32 as ffier::FfiType>::into_c(v)) };
        <Banana as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Banana {
    fn drop(&mut self) {
        unsafe { ft_banana_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_mango_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_mango_new(v: <i32 as ffier::FfiType>::CRepr) -> <Mango as ffier::FfiType>::CRepr;
}
pub struct Mango(*mut core::ffi::c_void);
impl Mango {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Mango {
    const C_HANDLE_NAME: &'static str = "Mango";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Mango {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Mango";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Mango {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Mango").field(&self.0).finish()
    }
}
impl Mango {
    pub fn new(v: i32) -> Mango {
        let __raw = unsafe { ft_mango_new(<i32 as ffier::FfiType>::into_c(v)) };
        <Mango as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Mango {
    fn drop(&mut self) {
        unsafe { ft_mango_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_peach_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_peach_new(v: <i32 as ffier::FfiType>::CRepr) -> <Peach as ffier::FfiType>::CRepr;
}
pub struct Peach(*mut core::ffi::c_void);
impl Peach {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Peach {
    const C_HANDLE_NAME: &'static str = "Peach";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Peach {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Peach";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Peach {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Peach").field(&self.0).finish()
    }
}
impl Peach {
    pub fn new(v: i32) -> Peach {
        let __raw = unsafe { ft_peach_new(<i32 as ffier::FfiType>::into_c(v)) };
        <Peach as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Peach {
    fn drop(&mut self) {
        unsafe { ft_peach_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_plum_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_plum_new(v: <i32 as ffier::FfiType>::CRepr) -> <Plum as ffier::FfiType>::CRepr;
}
pub struct Plum(*mut core::ffi::c_void);
impl Plum {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Plum {
    const C_HANDLE_NAME: &'static str = "Plum";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Plum {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Plum";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Plum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Plum").field(&self.0).finish()
    }
}
impl Plum {
    pub fn new(v: i32) -> Plum {
        let __raw = unsafe { ft_plum_new(<i32 as ffier::FfiType>::into_c(v)) };
        <Plum as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Plum {
    fn drop(&mut self) {
        unsafe { ft_plum_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_grape_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_grape_new(v: <i32 as ffier::FfiType>::CRepr) -> <Grape as ffier::FfiType>::CRepr;
}
pub struct Grape(*mut core::ffi::c_void);
impl Grape {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Grape {
    const C_HANDLE_NAME: &'static str = "Grape";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Grape {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Grape";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Grape {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Grape").field(&self.0).finish()
    }
}
impl Grape {
    pub fn new(v: i32) -> Grape {
        let __raw = unsafe { ft_grape_new(<i32 as ffier::FfiType>::into_c(v)) };
        <Grape as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Grape {
    fn drop(&mut self) {
        unsafe { ft_grape_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_lemon_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_lemon_new(v: <i32 as ffier::FfiType>::CRepr) -> <Lemon as ffier::FfiType>::CRepr;
}
pub struct Lemon(*mut core::ffi::c_void);
impl Lemon {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Lemon {
    const C_HANDLE_NAME: &'static str = "Lemon";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Lemon {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Lemon";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Lemon {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Lemon").field(&self.0).finish()
    }
}
impl Lemon {
    pub fn new(v: i32) -> Lemon {
        let __raw = unsafe { ft_lemon_new(<i32 as ffier::FfiType>::into_c(v)) };
        <Lemon as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Lemon {
    fn drop(&mut self) {
        unsafe { ft_lemon_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_mixer_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_mixer_new() -> <Mixer as ffier::FfiType>::CRepr;
    pub fn ft_mixer_add(handle: *mut *mut core::ffi::c_void, fruit: *mut core::ffi::c_void);
    pub fn ft_mixer_blend_concrete(
        handle: *mut core::ffi::c_void,
        a: *mut core::ffi::c_void,
        b: *mut core::ffi::c_void,
    ) -> <i32 as ffier::FfiType>::CRepr;
    pub fn ft_mixer_blend_hybrid(
        handle: *mut core::ffi::c_void,
        a: *mut core::ffi::c_void,
        b: *mut core::ffi::c_void,
    ) -> <i32 as ffier::FfiType>::CRepr;
    pub fn ft_mixer_blend_dynamic(
        handle: *mut core::ffi::c_void,
        a: *mut core::ffi::c_void,
        b: *mut core::ffi::c_void,
    ) -> <i32 as ffier::FfiType>::CRepr;
    pub fn ft_mixer_peek(
        handle: *mut core::ffi::c_void,
        fruit: *mut core::ffi::c_void,
    ) -> <i32 as ffier::FfiType>::CRepr;
    pub fn ft_mixer_peek_dyn(
        handle: *mut core::ffi::c_void,
        fruit: *mut core::ffi::c_void,
    ) -> <i32 as ffier::FfiType>::CRepr;
    pub fn ft_mixer_peek_sum(
        handle: *mut core::ffi::c_void,
        a: *mut core::ffi::c_void,
        b: *mut core::ffi::c_void,
    ) -> <i32 as ffier::FfiType>::CRepr;
    pub fn ft_mixer_total(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
}
pub struct Mixer(*mut core::ffi::c_void);
impl Mixer {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Mixer {
    const C_HANDLE_NAME: &'static str = "Mixer";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Mixer {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Mixer";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Mixer {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Mixer").field(&self.0).finish()
    }
}
impl Mixer {
    pub fn new() -> Mixer {
        let __raw = unsafe { ft_mixer_new() };
        <Mixer as ffier::FfiType>::from_c(__raw)
    }
    pub fn add(self, fruit: impl Fruit) -> Self {
        let mut __handle = {
            let this = std::mem::ManuallyDrop::new(self);
            this.0
        };
        unsafe { ft_mixer_add(&mut __handle, fruit.__into_raw_handle()) };
        Self(__handle)
    }
    #[doc = " Both concrete (9^2=81 > 64, override with annotation)."]
    pub fn blend_concrete(&mut self, a: impl Fruit, b: impl Fruit) -> i32 {
        let __raw = unsafe {
            ft_mixer_blend_concrete(self.0, a.__into_raw_handle(), b.__into_raw_handle())
        };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " First concrete, second vtable (hybrid: 9+9=18 branches)."]
    pub fn blend_hybrid(&mut self, a: impl Fruit, b: impl Fruit) -> i32 {
        let __raw =
            unsafe { ft_mixer_blend_hybrid(self.0, a.__into_raw_handle(), b.__into_raw_handle()) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Both vtable (9+9=18 branches)."]
    pub fn blend_dynamic(&mut self, a: impl Fruit, b: impl Fruit) -> i32 {
        let __raw =
            unsafe { ft_mixer_blend_dynamic(self.0, a.__into_raw_handle(), b.__into_raw_handle()) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Peek via borrowed impl Trait (concrete dispatch, borrow)."]
    pub fn peek(&self, fruit: &impl Fruit) -> i32 {
        let mut __fruit_href = fruit.__as_handle();
        let __raw = unsafe { ft_mixer_peek(self.0, __fruit_href.as_ptr()) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    #[doc = " Peek two fruits by ref without consuming."]
    #[doc = " Peek via dyn ref."]
    pub fn peek_dyn(&self, fruit: &dyn Fruit) -> i32 {
        let mut __fruit_href = fruit.__as_handle_dyn();
        let __raw = unsafe { ft_mixer_peek_dyn(self.0, __fruit_href.as_ptr()) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    pub fn peek_sum(&self, a: &impl Fruit, b: &impl Fruit) -> i32 {
        let mut __a_href = a.__as_handle();
        let mut __b_href = b.__as_handle();
        let __raw = unsafe { ft_mixer_peek_sum(self.0, __a_href.as_ptr(), __b_href.as_ptr()) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    pub fn total(&self) -> i32 {
        let __raw = unsafe { ft_mixer_total(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Mixer {
    fn drop(&mut self) {
        unsafe { ft_mixer_destroy(self.0) }
    }
}
unsafe extern "C" {
    pub fn ft_sprocket_destroy(handle: *mut core::ffi::c_void);
    pub fn ft_sprocket_new(
        name: <&'static str as ffier::FfiType>::CRepr,
    ) -> <Sprocket as ffier::FfiType>::CRepr;
}
pub struct Sprocket(*mut core::ffi::c_void);
impl Sprocket {
    #[doc(hidden)]
    pub fn __from_raw(ptr: *mut core::ffi::c_void) -> Self {
        Self(ptr)
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl ffier::FfiHandle for Sprocket {
    const C_HANDLE_NAME: &'static str = "Sprocket";
    fn as_handle(&self) -> *mut core::ffi::c_void {
        self.0
    }
}
impl ffier::FfiType for Sprocket {
    type CRepr = *mut core::ffi::c_void;
    const C_TYPE_NAME: &'static str = "Sprocket";
    fn into_c(self) -> *mut core::ffi::c_void {
        self.__into_raw()
    }
    fn from_c(repr: *mut core::ffi::c_void) -> Self {
        Self::__from_raw(repr)
    }
}
impl std::fmt::Debug for Sprocket {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_tuple("Sprocket").field(&self.0).finish()
    }
}
impl Sprocket {
    pub fn new(name: &str) -> Sprocket {
        let __raw = unsafe { ft_sprocket_new(<&str as ffier::FfiType>::into_c(name)) };
        <Sprocket as ffier::FfiType>::from_c(__raw)
    }
}
impl Drop for Sprocket {
    fn drop(&mut self) {
        unsafe { ft_sprocket_destroy(self.0) }
    }
}
pub trait Processor {
    fn process(&self, input: i32) -> i32;
    fn name(&self) -> &str;
    fn on_notify(&self, code: i32);
    #[doc = r" Convert this value into an opaque FFI handle via vtable dispatch."]
    #[doc = r""]
    #[doc = r" Known types (with `#[ffier::trait_impl]`) override this with"]
    #[doc = r" direct handle passthrough. User types get the default"]
    #[doc = r" implementation which builds a const-promoted static vtable."]
    #[doc(hidden)]
    fn __into_raw_handle(self) -> *mut core::ffi::c_void
    where
        Self: Sized,
    {
        let __vtable: &'static ProcessorVtable = &ProcessorVtable {
            process: {
                unsafe extern "C" fn __trampoline<__T: Processor>(
                    __ud: *mut core::ffi::c_void,
                    input: <i32 as ffier::FfiType>::CRepr,
                ) -> <i32 as ffier::FfiType>::CRepr {
                    let __obj = unsafe { &*(__ud as *const __T) };
                    let __result = __obj.process(<i32 as ffier::FfiType>::from_c(input));
                    <i32 as ffier::FfiType>::into_c(__result)
                }
                __trampoline::<Self>
            },
            name: {
                unsafe extern "C" fn __trampoline<__T: Processor>(
                    __ud: *mut core::ffi::c_void,
                ) -> <&'static str as ffier::FfiType>::CRepr {
                    let __obj = unsafe { &*(__ud as *const __T) };
                    let __result = __obj.name();
                    <&str as ffier::FfiType>::into_c(__result)
                }
                __trampoline::<Self>
            },
            on_notify: {
                unsafe extern "C" fn __trampoline<__T: Processor>(
                    __ud: *mut core::ffi::c_void,
                    code: <i32 as ffier::FfiType>::CRepr,
                ) {
                    let __obj = unsafe { &*(__ud as *const __T) };
                    let __result = __obj.on_notify(<i32 as ffier::FfiType>::from_c(code));
                    __result
                }
                __trampoline::<Self>
            },
            drop: Some({
                unsafe extern "C" fn __trampoline<__T>(__ud: *mut core::ffi::c_void) {
                    unsafe { drop(Box::from_raw(__ud as *mut __T)) };
                }
                __trampoline::<Self>
            }),
        };
        let __ud = Box::into_raw(Box::new(self)) as *mut core::ffi::c_void;
        VtableProcessor::new(__ud, __vtable).__into_raw()
    }
    #[doc(hidden)]
    fn __as_handle(&self) -> ffier::FfierHandleRef
    where
        Self: Sized,
    {
        let __vtable: &'static ProcessorVtable = &ProcessorVtable {
            process: {
                unsafe extern "C" fn __trampoline<__T: Processor>(
                    __ud: *mut core::ffi::c_void,
                    input: <i32 as ffier::FfiType>::CRepr,
                ) -> <i32 as ffier::FfiType>::CRepr {
                    let __obj = unsafe { &*(__ud as *const __T) };
                    let __result = __obj.process(<i32 as ffier::FfiType>::from_c(input));
                    <i32 as ffier::FfiType>::into_c(__result)
                }
                __trampoline::<Self>
            },
            name: {
                unsafe extern "C" fn __trampoline<__T: Processor>(
                    __ud: *mut core::ffi::c_void,
                ) -> <&'static str as ffier::FfiType>::CRepr {
                    let __obj = unsafe { &*(__ud as *const __T) };
                    let __result = __obj.name();
                    <&str as ffier::FfiType>::into_c(__result)
                }
                __trampoline::<Self>
            },
            on_notify: {
                unsafe extern "C" fn __trampoline<__T: Processor>(
                    __ud: *mut core::ffi::c_void,
                    code: <i32 as ffier::FfiType>::CRepr,
                ) {
                    let __obj = unsafe { &*(__ud as *const __T) };
                    let __result = __obj.on_notify(<i32 as ffier::FfiType>::from_c(code));
                    __result
                }
                __trampoline::<Self>
            },
            drop: None,
        };
        ffier::FfierHandleRef::Tagged(ffier::FfierTaggedRef {
            type_id: core::any::TypeId::of::<VtableProcessor>(),
            user_data: self as *const Self as *const core::ffi::c_void,
            vtable: __vtable as *const ProcessorVtable as *const core::ffi::c_void,
        })
    }
    #[doc = r" Object-safe version for &dyn Trait dispatch."]
    #[doc = r" Builds a FfierDynRef with C vtable trampolines that call through"]
    #[doc = r" Rust's native dyn dispatch. Known types override with Handle(self.0)."]
    #[doc(hidden)]
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        let __c_vtable: &'static ProcessorVtable = &ProcessorVtable {
            process: {
                unsafe extern "C" fn __dyn_trampoline(
                    __ud: *mut core::ffi::c_void,
                    input: <i32 as ffier::FfiType>::CRepr,
                ) -> <i32 as ffier::FfiType>::CRepr {
                    let __fat_parts = unsafe { &*(__ud as *const [*const core::ffi::c_void; 2]) };
                    let __obj: &dyn Processor = unsafe {
                        core::mem::transmute::<
                            (*const core::ffi::c_void, *const core::ffi::c_void),
                            &dyn Processor,
                        >((__fat_parts[0], __fat_parts[1]))
                    };
                    let __result = __obj.process(<i32 as ffier::FfiType>::from_c(input));
                    <i32 as ffier::FfiType>::into_c(__result)
                }
                __dyn_trampoline
            },
            name: {
                unsafe extern "C" fn __dyn_trampoline(
                    __ud: *mut core::ffi::c_void,
                ) -> <&'static str as ffier::FfiType>::CRepr {
                    let __fat_parts = unsafe { &*(__ud as *const [*const core::ffi::c_void; 2]) };
                    let __obj: &dyn Processor = unsafe {
                        core::mem::transmute::<
                            (*const core::ffi::c_void, *const core::ffi::c_void),
                            &dyn Processor,
                        >((__fat_parts[0], __fat_parts[1]))
                    };
                    let __result = __obj.name();
                    <&str as ffier::FfiType>::into_c(__result)
                }
                __dyn_trampoline
            },
            on_notify: {
                unsafe extern "C" fn __dyn_trampoline(
                    __ud: *mut core::ffi::c_void,
                    code: <i32 as ffier::FfiType>::CRepr,
                ) {
                    let __fat_parts = unsafe { &*(__ud as *const [*const core::ffi::c_void; 2]) };
                    let __obj: &dyn Processor = unsafe {
                        core::mem::transmute::<
                            (*const core::ffi::c_void, *const core::ffi::c_void),
                            &dyn Processor,
                        >((__fat_parts[0], __fat_parts[1]))
                    };
                    let __result = __obj.on_notify(<i32 as ffier::FfiType>::from_c(code));
                    __result
                }
                __dyn_trampoline
            },
            drop: None,
        };
        let __fat: [*const core::ffi::c_void; 2] = unsafe {
            let mut parts = [core::ptr::null(); 2];
            let src = &self as *const &Self as *const *const core::ffi::c_void;
            parts[0] = *src;
            if core::mem::size_of::<&Self>() == 2 * core::mem::size_of::<*const ()>() {
                parts[1] = *src.add(1);
            }
            parts
        };
        ffier::FfierHandleRef::DynRef(ffier::FfierDynRef {
            type_id: core::any::TypeId::of::<VtableProcessor>(),
            user_data: core::ptr::null(),
            c_vtable: __c_vtable as *const ProcessorVtable as *const core::ffi::c_void,
            fat_ptr: __fat,
        })
    }
}
#[repr(C)]
pub struct ProcessorVtable {
    pub process: unsafe extern "C" fn(
        *mut core::ffi::c_void,
        <i32 as ffier::FfiType>::CRepr,
    ) -> <i32 as ffier::FfiType>::CRepr,
    pub name:
        unsafe extern "C" fn(*mut core::ffi::c_void) -> <&'static str as ffier::FfiType>::CRepr,
    pub on_notify: unsafe extern "C" fn(*mut core::ffi::c_void, <i32 as ffier::FfiType>::CRepr),
    pub drop: Option<unsafe extern "C" fn(*mut core::ffi::c_void)>,
}
unsafe extern "C" {
    pub fn ft_processor_from_vtable(
        user_data: *mut core::ffi::c_void,
        vtable: *const ProcessorVtable,
    ) -> *mut core::ffi::c_void;
}
pub struct VtableProcessor(*mut core::ffi::c_void);
impl VtableProcessor {
    pub fn new(user_data: *mut core::ffi::c_void, vtable: &ProcessorVtable) -> Self {
        Self(unsafe { ft_processor_from_vtable(user_data, vtable) })
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl Drop for VtableProcessor {
    fn drop(&mut self) {}
}
pub trait Fruit {
    fn value(&self) -> i32;
    #[doc = r" Convert this value into an opaque FFI handle via vtable dispatch."]
    #[doc = r""]
    #[doc = r" Known types (with `#[ffier::trait_impl]`) override this with"]
    #[doc = r" direct handle passthrough. User types get the default"]
    #[doc = r" implementation which builds a const-promoted static vtable."]
    #[doc(hidden)]
    fn __into_raw_handle(self) -> *mut core::ffi::c_void
    where
        Self: Sized,
    {
        let __vtable: &'static FruitVtable = &FruitVtable {
            value: {
                unsafe extern "C" fn __trampoline<__T: Fruit>(
                    __ud: *mut core::ffi::c_void,
                ) -> <i32 as ffier::FfiType>::CRepr {
                    let __obj = unsafe { &*(__ud as *const __T) };
                    let __result = __obj.value();
                    <i32 as ffier::FfiType>::into_c(__result)
                }
                __trampoline::<Self>
            },
            drop: Some({
                unsafe extern "C" fn __trampoline<__T>(__ud: *mut core::ffi::c_void) {
                    unsafe { drop(Box::from_raw(__ud as *mut __T)) };
                }
                __trampoline::<Self>
            }),
        };
        let __ud = Box::into_raw(Box::new(self)) as *mut core::ffi::c_void;
        VtableFruit::new(__ud, __vtable).__into_raw()
    }
    #[doc(hidden)]
    fn __as_handle(&self) -> ffier::FfierHandleRef
    where
        Self: Sized,
    {
        let __vtable: &'static FruitVtable = &FruitVtable {
            value: {
                unsafe extern "C" fn __trampoline<__T: Fruit>(
                    __ud: *mut core::ffi::c_void,
                ) -> <i32 as ffier::FfiType>::CRepr {
                    let __obj = unsafe { &*(__ud as *const __T) };
                    let __result = __obj.value();
                    <i32 as ffier::FfiType>::into_c(__result)
                }
                __trampoline::<Self>
            },
            drop: None,
        };
        ffier::FfierHandleRef::Tagged(ffier::FfierTaggedRef {
            type_id: core::any::TypeId::of::<VtableFruit>(),
            user_data: self as *const Self as *const core::ffi::c_void,
            vtable: __vtable as *const FruitVtable as *const core::ffi::c_void,
        })
    }
    #[doc = r" Object-safe version for &dyn Trait dispatch."]
    #[doc = r" Builds a FfierDynRef with C vtable trampolines that call through"]
    #[doc = r" Rust's native dyn dispatch. Known types override with Handle(self.0)."]
    #[doc(hidden)]
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        let __c_vtable: &'static FruitVtable = &FruitVtable {
            value: {
                unsafe extern "C" fn __dyn_trampoline(
                    __ud: *mut core::ffi::c_void,
                ) -> <i32 as ffier::FfiType>::CRepr {
                    let __fat_parts = unsafe { &*(__ud as *const [*const core::ffi::c_void; 2]) };
                    let __obj: &dyn Fruit = unsafe {
                        core::mem::transmute::<
                            (*const core::ffi::c_void, *const core::ffi::c_void),
                            &dyn Fruit,
                        >((__fat_parts[0], __fat_parts[1]))
                    };
                    let __result = __obj.value();
                    <i32 as ffier::FfiType>::into_c(__result)
                }
                __dyn_trampoline
            },
            drop: None,
        };
        let __fat: [*const core::ffi::c_void; 2] = unsafe {
            let mut parts = [core::ptr::null(); 2];
            let src = &self as *const &Self as *const *const core::ffi::c_void;
            parts[0] = *src;
            if core::mem::size_of::<&Self>() == 2 * core::mem::size_of::<*const ()>() {
                parts[1] = *src.add(1);
            }
            parts
        };
        ffier::FfierHandleRef::DynRef(ffier::FfierDynRef {
            type_id: core::any::TypeId::of::<VtableFruit>(),
            user_data: core::ptr::null(),
            c_vtable: __c_vtable as *const FruitVtable as *const core::ffi::c_void,
            fat_ptr: __fat,
        })
    }
}
#[repr(C)]
pub struct FruitVtable {
    pub value: unsafe extern "C" fn(*mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr,
    pub drop: Option<unsafe extern "C" fn(*mut core::ffi::c_void)>,
}
unsafe extern "C" {
    pub fn ft_fruit_from_vtable(
        user_data: *mut core::ffi::c_void,
        vtable: *const FruitVtable,
    ) -> *mut core::ffi::c_void;
}
pub struct VtableFruit(*mut core::ffi::c_void);
impl VtableFruit {
    pub fn new(user_data: *mut core::ffi::c_void, vtable: &FruitVtable) -> Self {
        Self(unsafe { ft_fruit_from_vtable(user_data, vtable) })
    }
    #[doc(hidden)]
    pub fn __into_raw(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
}
impl Drop for VtableFruit {
    fn drop(&mut self) {}
}
unsafe extern "C" {
    pub fn ft_apple_value(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
}
impl Fruit for Apple {
    fn value(&self) -> i32 {
        let __raw = unsafe { ft_apple_value(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
    fn __as_handle(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
}
unsafe extern "C" {
    pub fn ft_orange_value(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
}
impl Fruit for Orange {
    fn value(&self) -> i32 {
        let __raw = unsafe { ft_orange_value(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
    fn __as_handle(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
}
unsafe extern "C" {
    pub fn ft_banana_value(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
}
impl Fruit for Banana {
    fn value(&self) -> i32 {
        let __raw = unsafe { ft_banana_value(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
    fn __as_handle(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
}
unsafe extern "C" {
    pub fn ft_mango_value(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
}
impl Fruit for Mango {
    fn value(&self) -> i32 {
        let __raw = unsafe { ft_mango_value(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
    fn __as_handle(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
}
unsafe extern "C" {
    pub fn ft_peach_value(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
}
impl Fruit for Peach {
    fn value(&self) -> i32 {
        let __raw = unsafe { ft_peach_value(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
    fn __as_handle(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
}
unsafe extern "C" {
    pub fn ft_plum_value(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
}
impl Fruit for Plum {
    fn value(&self) -> i32 {
        let __raw = unsafe { ft_plum_value(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
    fn __as_handle(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
}
unsafe extern "C" {
    pub fn ft_grape_value(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
}
impl Fruit for Grape {
    fn value(&self) -> i32 {
        let __raw = unsafe { ft_grape_value(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
    fn __as_handle(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
}
unsafe extern "C" {
    pub fn ft_lemon_value(handle: *mut core::ffi::c_void) -> <i32 as ffier::FfiType>::CRepr;
}
impl Fruit for Lemon {
    fn value(&self) -> i32 {
        let __raw = unsafe { ft_lemon_value(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
    fn __as_handle(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
}
pub trait Attachment {
    fn label(&self) -> &str;
    #[doc(hidden)]
    fn __into_raw_handle(self) -> *mut core::ffi::c_void
    where
        Self: Sized;
    #[doc(hidden)]
    fn __as_handle(&self) -> ffier::FfierHandleRef
    where
        Self: Sized;
    #[doc(hidden)]
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        unimplemented!("&dyn dispatch requires #[ffier::implementable] on the trait")
    }
}
unsafe extern "C" {
    pub fn ft_sprocket_label(
        handle: *mut core::ffi::c_void,
    ) -> <&'static str as ffier::FfiType>::CRepr;
}
impl Attachment for Sprocket {
    fn label(&self) -> &str {
        let __raw = unsafe { ft_sprocket_label(self.0) };
        <&str as ffier::FfiType>::from_c(__raw)
    }
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
    fn __as_handle(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
}
pub trait Snapshot<'a> {
    fn snap_description(&self) -> &str;
    fn snap_source_count(&self) -> i32;
    #[doc(hidden)]
    fn __into_raw_handle(self) -> *mut core::ffi::c_void
    where
        Self: Sized;
    #[doc(hidden)]
    fn __as_handle(&self) -> ffier::FfierHandleRef
    where
        Self: Sized;
    #[doc(hidden)]
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        unimplemented!("&dyn dispatch requires #[ffier::implementable] on the trait")
    }
}
unsafe extern "C" {
    pub fn ft_view_snap_description(
        handle: *mut core::ffi::c_void,
    ) -> <&'static str as ffier::FfiType>::CRepr;
    pub fn ft_view_snap_source_count(
        handle: *mut core::ffi::c_void,
    ) -> <i32 as ffier::FfiType>::CRepr;
}
impl<'a> Snapshot<'a> for View<'a> {
    fn snap_description(&self) -> &str {
        let __raw = unsafe { ft_view_snap_description(self.0) };
        <&str as ffier::FfiType>::from_c(__raw)
    }
    fn snap_source_count(&self) -> i32 {
        let __raw = unsafe { ft_view_snap_source_count(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
    fn __as_handle(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
}
unsafe extern "C" {
    pub fn ft_widget_snap_description(
        handle: *mut core::ffi::c_void,
    ) -> <&'static str as ffier::FfiType>::CRepr;
    pub fn ft_widget_snap_source_count(
        handle: *mut core::ffi::c_void,
    ) -> <i32 as ffier::FfiType>::CRepr;
}
impl Snapshot<'static> for Widget {
    fn snap_description(&self) -> &str {
        let __raw = unsafe { ft_widget_snap_description(self.0) };
        <&str as ffier::FfiType>::from_c(__raw)
    }
    fn snap_source_count(&self) -> i32 {
        let __raw = unsafe { ft_widget_snap_source_count(self.0) };
        <i32 as ffier::FfiType>::from_c(__raw)
    }
    fn __into_raw_handle(self) -> *mut core::ffi::c_void {
        let this = std::mem::ManuallyDrop::new(self);
        this.0
    }
    fn __as_handle(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
    fn __as_handle_dyn(&self) -> ffier::FfierHandleRef {
        ffier::FfierHandleRef::Handle(self.0)
    }
}
