//! C header generator from ffier JSON schema.
//!
//! Reads a `ffier-{prefix}.json` and produces a complete C header with:
//! - Handle typedefs (`typedef void* FtWidget;`)
//! - Shared type infrastructure (`FtStr`, `FtBytes`, `FtResult`, macros)
//! - Error code `#define`s
//! - Function declarations with doc comments

use ffier_schema::{
    ErrorType, ExportedType, Library, Method, MethodContext, ParamKind, Receiver, Return,
};

/// Generate a C header string from a library schema.
pub fn generate(lib: &Library, guard: &str) -> String {
    let mut out = String::new();
    let type_pfx = snake_to_pascal(&lib.prefix);
    let upper_pfx = format!("{}_", lib.prefix.to_ascii_uppercase());

    // Header guard + includes
    out.push_str(&format!("#ifndef {guard}\n"));
    out.push_str(&format!("#define {guard}\n\n"));
    out.push_str("#include <stddef.h>\n");
    out.push_str("#include <stdint.h>\n");
    out.push_str("#include <stdbool.h>\n");
    out.push_str("#include <string.h>\n\n");

    // Handle typedefs
    for ty in &lib.types {
        out.push_str(&format!("typedef void* {};\n", ty.c_name));
    }
    for err in &lib.errors {
        out.push_str(&format!("typedef void* {};\n", err.c_name));
    }
    out.push('\n');

    // Shared types
    emit_shared_types(&mut out, &type_pfx, &upper_pfx);

    out.push_str("/* Header auto-generated by ffier */\n");

    // Error sections
    for err in &lib.errors {
        emit_error_section(&mut out, err);
    }

    // Type sections
    for ty in &lib.types {
        emit_type_section(&mut out, ty, &type_pfx, &upper_pfx, lib);
    }

    out.push('\n');
    out.push_str(&format!("#endif /* {guard} */\n"));
    out
}

/// Generate a C header from a JSON file path.
pub fn generate_from_file(
    json_path: &str,
    guard: &str,
) -> Result<String, Box<dyn std::error::Error>> {
    let json = std::fs::read_to_string(json_path)?;
    let lib = Library::from_json(&json)?;
    Ok(generate(&lib, guard))
}

fn emit_shared_types(out: &mut String, type_pfx: &str, upper_pfx: &str) {
    let result_c = format!("{type_pfx}Result");
    let error_c = format!("{type_pfx}Error");
    let str_c = format!("{type_pfx}Str");
    let bytes_c = format!("{type_pfx}Bytes");
    let path_c = format!("{type_pfx}Path");
    let result_success = format!("{upper_pfx}RESULT_SUCCESS");
    let str_macro = format!("{upper_pfx}STR");
    let bytes_macro = format!("{upper_pfx}BYTES");

    out.push_str(&format!("typedef uint64_t {result_c};\n"));
    out.push_str(&format!("#define {result_success} 0\n\n"));
    out.push_str("/* Opaque error handle — pass to *_error_message() for details, free with *_error_destroy() */\n");
    out.push_str(&format!("typedef void* {error_c};\n\n"));
    out.push_str("/* Caller must ensure data is valid UTF-8 */\n");
    out.push_str("typedef struct {\n");
    out.push_str("    const char* data;\n");
    out.push_str("    size_t len;\n");
    out.push_str(&format!("}} {str_c};\n\n"));
    out.push_str("/* Caller must ensure data is a valid UTF-8 path */\n");
    out.push_str(&format!("typedef {str_c} {path_c};\n\n"));
    out.push_str("typedef struct {\n");
    out.push_str("    const uint8_t* data;\n");
    out.push_str("    size_t len;\n");
    out.push_str(&format!("}} {bytes_c};\n\n"));
    out.push_str(&format!(
        "#define {str_macro}(s) (({str_c}){{ .data = (s), .len = strlen(s) }})\n"
    ));
    out.push_str("#if defined(__GNUC__)\n");
    out.push_str(&format!("#define {bytes_macro}(arr) ({{ \\\n"));
    out.push_str("    _Static_assert( \\\n");
    out.push_str("        !__builtin_types_compatible_p(typeof(arr), typeof(&(arr)[0])), \\\n");
    out.push_str(&format!(
        "        \"{bytes_macro}() requires an array, not a pointer\"); \\\n"
    ));
    out.push_str(&format!(
        "    (({bytes_c}){{ .data = (const uint8_t*)(arr), .len = sizeof(arr) }}); \\\n"
    ));
    out.push_str("})\n");
    out.push_str("#else\n");
    out.push_str(&format!("#define {bytes_macro}(arr) \\\n"));
    out.push_str(&format!(
        "    (({bytes_c}){{ .data = (const uint8_t*)(arr), .len = sizeof(arr) }})\n"
    ));
    out.push_str("#endif\n");
}

fn emit_error_section(out: &mut String, err: &ErrorType) {
    out.push_str(&format!("\n/* {} ", err.name));
    let dashes = "-".repeat(72 - 6 - err.name.len());
    out.push_str(&dashes);
    out.push_str(" */\n\n");

    for v in &err.variants {
        out.push_str(&format!(
            "#define {} ((uint64_t){} << 32 | {})\n",
            v.c_name, err.type_tag, v.code,
        ));
    }
}

fn emit_type_section(
    out: &mut String,
    ty: &ExportedType,
    type_pfx: &str,
    _upper_pfx: &str,
    lib: &Library,
) {
    out.push_str(&format!("\n/* {} ", ty.name));
    let dashes = "-".repeat(72 - 6 - ty.name.len());
    out.push_str(&dashes);
    out.push_str(" */\n\n");

    for m in &ty.methods {
        let MethodContext::Exportable {
            ffi_name,
            is_builder,
        } = &m.context
        else {
            continue;
        };

        // Doc comments
        emit_doc_comment(out, &m.doc);

        // Build the C declaration
        let decl = format_c_declaration(ffi_name, &ty.c_name, m, *is_builder, type_pfx, lib);
        out.push_str(&decl);
        out.push('\n');
    }
}

fn emit_doc_comment(out: &mut String, doc: &[String]) {
    if doc.is_empty() {
        return;
    }
    if doc.len() == 1 {
        out.push_str(&format!("/**{} */\n", doc[0]));
    } else {
        out.push_str("/**\n");
        for line in doc {
            out.push_str(&format!(" *{line}\n"));
        }
        out.push_str(" */\n");
    }
}

fn format_c_declaration(
    ffi_name: &str,
    handle_c_name: &str,
    m: &Method,
    is_builder: bool,
    type_pfx: &str,
    lib: &Library,
) -> String {
    let mut params: Vec<String> = Vec::new();

    // Handle param (self)
    if m.receiver != Receiver::None {
        params.push(format!("{handle_c_name} handle"));
    }

    // Regular params
    for p in &m.params {
        match &p.kind {
            ParamKind::Regular => {
                params.push(format!("{} {}", p.c_type, p.name));
            }
            ParamKind::StrSlice => {
                let str_c = format!("{type_pfx}Str");
                params.push(format!("const {str_c}* {}", p.name));
                params.push(format!("size_t {}_len", p.name));
            }
            ParamKind::ImplTrait { .. } => {
                params.push(format!("void* {}", p.name));
            }
        }
    }

    // Return type handling
    let (ret_type, extra_params) = match &m.ret {
        Return::Void => ("void".to_string(), vec![]),
        Return::Value { c_type, .. } => {
            if is_builder {
                ("void".to_string(), vec![])
            } else {
                (c_type.clone(), vec![])
            }
        }
        Return::Result { ok, err_type } => {
            let error_c_name = find_error_c_name(lib, err_type);
            match ok {
                None => {
                    // Result<(), E> → FtResult fn(..., FtError* err_out)
                    let result_c = format!("{type_pfx}Result");
                    (result_c, vec![format!("{error_c_name}* err_out")])
                }
                Some(ok_val) if ok_val.is_handle => {
                    // Result<Handle, E> → Handle fn(..., FtError* err_out)
                    // Returns null on error.
                    (
                        ok_val.c_type.clone(),
                        vec![format!("{error_c_name}* err_out")],
                    )
                }
                Some(ok_val) => {
                    // Result<T, E> → FtResult fn(..., T* result, FtError* err_out)
                    let result_c = format!("{type_pfx}Result");
                    (
                        result_c,
                        vec![
                            format!("{}* result", ok_val.c_type),
                            format!("{error_c_name}* err_out"),
                        ],
                    )
                }
            }
        }
    };

    params.extend(extra_params);

    let params_str = if params.is_empty() {
        "void".to_string()
    } else {
        params.join(", ")
    };

    format!("{ret_type} {ffi_name}({params_str});")
}

fn find_error_c_name(lib: &Library, _err_type: &str) -> String {
    // TODO: if multiple error types exist, match by err_type name
    let type_pfx = snake_to_pascal(&lib.prefix);
    format!("{type_pfx}Error")
}

fn snake_to_pascal(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => c.to_uppercase().collect::<String>() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}
