use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{
    FnArg, GenericArgument, ImplItem, ItemImpl, Pat, PathArguments, ReturnType, Type,
    parse_macro_input,
};

#[proc_macro_attribute]
pub fn reflect(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let input = parse_macro_input!(item as ItemImpl);
    let impl_block = input.clone();

    let Type::Path(ref struct_path) = *input.self_ty else {
        return syn::Error::new_spanned(&input.self_ty, "expected a named struct type")
            .to_compile_error()
            .into();
    };
    let struct_ident = struct_path.path.get_ident().expect("expected simple struct name");
    let struct_name = struct_ident.to_string();
    let struct_lower = struct_name.to_lowercase();

    let trait_path = input.trait_.as_ref().map(|(_, path, _)| path);

    let mut ffi_fns = Vec::new();
    let mut header_exprs: Vec<proc_macro2::TokenStream> = Vec::new();

    header_exprs.push(quote! { concat!("/* Auto-generated by ffier for ", #struct_name, " */") });
    header_exprs.push(quote! { "#pragma once" });
    header_exprs.push(quote! { "#include <stdint.h>" });
    header_exprs.push(quote! { "#include <stdbool.h>" });
    header_exprs.push(quote! { "" });

    // Shared FfierError base struct (include-guarded)
    header_exprs.push(quote! { "#ifndef FFIER_ERROR_DEFINED" });
    header_exprs.push(quote! { "#define FFIER_ERROR_DEFINED" });
    header_exprs.push(quote! { "typedef struct {" });
    header_exprs.push(quote! { "    uint64_t code;" });
    header_exprs.push(quote! { "    char* _msg; /* private - use *_message() */" });
    header_exprs.push(quote! { "} FfierError;" });
    header_exprs.push(quote! { "" });
    header_exprs.push(quote! { "void ffier_error_free(FfierError* err);" });
    header_exprs.push(quote! { "#endif /* FFIER_ERROR_DEFINED */" });
    header_exprs.push(quote! { "" });

    header_exprs.push(quote! { concat!("typedef void* ", #struct_name, "Handle;") });
    header_exprs.push(quote! { "" });

    let mut reexport_types: Vec<Type> = Vec::new();
    let mut reexport_aliases: Vec<syn::Ident> = Vec::new();
    let helper_mod_name = format_ident!("_ffier_{struct_lower}");

    enum ReturnKind {
        Void,
        Value(proc_macro2::TokenStream),
        Result {
            ok_ty: Option<proc_macro2::TokenStream>,
            err_ty: proc_macro2::TokenStream,
            /// Original error type ident (e.g. CalcError) for naming C functions
            err_ident: String,
        },
    }

    struct MethodInfo {
        method_name: syn::Ident,
        ffi_name: syn::Ident,
        ffi_name_str: String,
        is_mut: bool,
        param_idents: Vec<syn::Ident>,
        param_name_strs: Vec<String>,
        param_type_tokens: Vec<proc_macro2::TokenStream>,
        ret: ReturnKind,
    }

    let mut methods = Vec::new();
    let mut alias_counter = 0u32;

    for item in &input.items {
        let ImplItem::Fn(method) = item else { continue };
        let method_name = &method.sig.ident;
        let ffi_name = format_ident!("{struct_lower}_{method_name}");
        let ffi_name_str = ffi_name.to_string();

        let self_arg = method.sig.inputs.first();
        if !matches!(self_arg, Some(FnArg::Receiver(_))) {
            continue;
        }
        let receiver = match self_arg.unwrap() {
            FnArg::Receiver(r) => r,
            _ => unreachable!(),
        };
        let is_mut = receiver.mutability.is_some();

        let mut param_idents = Vec::new();
        let mut param_name_strs = Vec::new();
        let mut param_type_tokens = Vec::new();

        for arg in method.sig.inputs.iter().skip(1) {
            let FnArg::Typed(pat_ty) = arg else { continue };
            let Pat::Ident(pat_ident) = &*pat_ty.pat else { continue };
            param_idents.push(pat_ident.ident.clone());
            param_name_strs.push(pat_ident.ident.to_string());
            param_type_tokens.push(type_tokens_for_macro(
                &pat_ty.ty,
                &mut reexport_types,
                &mut reexport_aliases,
                &mut alias_counter,
                &helper_mod_name,
            ));
        }

        let ret = match &method.sig.output {
            ReturnType::Default => ReturnKind::Void,
            ReturnType::Type(_, ty) => {
                if let Some((ok, err)) = extract_result_types(ty) {
                    let err_ident = type_ident_name(&err);
                    let err_tokens = type_tokens_for_macro(
                        &err,
                        &mut reexport_types,
                        &mut reexport_aliases,
                        &mut alias_counter,
                        &helper_mod_name,
                    );
                    let ok_tokens = if is_unit_type(&ok) {
                        None
                    } else {
                        Some(type_tokens_for_macro(
                            &ok,
                            &mut reexport_types,
                            &mut reexport_aliases,
                            &mut alias_counter,
                            &helper_mod_name,
                        ))
                    };
                    ReturnKind::Result {
                        ok_ty: ok_tokens,
                        err_ty: err_tokens,
                        err_ident,
                    }
                } else {
                    ReturnKind::Value(type_tokens_for_macro(
                        ty,
                        &mut reexport_types,
                        &mut reexport_aliases,
                        &mut alias_counter,
                        &helper_mod_name,
                    ))
                }
            }
        };

        methods.push(MethodInfo {
            method_name: method_name.clone(),
            ffi_name,
            ffi_name_str,
            is_mut,
            param_idents,
            param_name_strs,
            param_type_tokens,
            ret,
        });
    }

    // Collect unique error types and generate per-type C artifacts
    let mut generated_error_types: Vec<String> = Vec::new();

    for m in &methods {
        if let ReturnKind::Result {
            err_ty, err_ident, ..
        } = &m.ret
        {
            if generated_error_types.contains(err_ident) {
                continue;
            }
            generated_error_types.push(err_ident.clone());

            let err_snake = camel_to_snake(err_ident);
            let err_upper = camel_to_upper_snake(err_ident);
            let message_fn_name = format_ident!("{err_snake}_message");
            let message_fn_name_str = message_fn_name.to_string();

            // Header: typedef + #defines + message function declaration
            header_exprs.push(quote! {
                concat!("typedef FfierError ", #err_ident, ";")
            });

            // #defines from FfiError::codes()
            header_exprs.push(quote! {{
                let mut s = String::new();
                for (name, val) in <#err_ty as ffier::FfiError>::codes() {
                    s.push_str(&format!("#define {}_{} {}\n", #err_upper, name, val));
                }
                s.push_str(&format!("\nconst char* {}(const {}* err);", #message_fn_name_str, #err_ident));
                s
            }});
            header_exprs.push(quote! { "" });

            // Generate the per-type _message function
            ffi_fns.push(quote! {
                #[unsafe(no_mangle)]
                pub unsafe extern "C" fn #message_fn_name(
                    err: *const ffier::FfierError,
                ) -> *const core::ffi::c_char {
                    let err = unsafe { &*err };
                    let ptr = err.msg_ptr();
                    if !ptr.is_null() {
                        return ptr;
                    }
                    <#err_ty as ffier::FfiError>::static_message(err.code).as_ptr()
                }
            });
        }
    }

    for m in &methods {
        let ffi_name_str = &m.ffi_name_str;
        let ffi_name = &m.ffi_name;
        let method_name = &m.method_name;
        let handle_type = format!("{struct_name}Handle handle");

        let cast = if m.is_mut {
            quote! { &mut *(handle as *mut $struct_ty) }
        } else {
            quote! { &*(handle as *const $struct_ty) }
        };

        let ffi_params: Vec<_> = m
            .param_idents
            .iter()
            .zip(m.param_type_tokens.iter())
            .map(|(id, ty)| quote! { #id: <#ty as ffier::FfiType>::CRepr })
            .collect();

        let converted_args: Vec<_> = m
            .param_idents
            .iter()
            .zip(m.param_type_tokens.iter())
            .map(|(id, ty)| quote! { <#ty as ffier::FfiType>::from_c(#id) })
            .collect();

        let param_c_type_exprs: Vec<_> = m
            .param_type_tokens
            .iter()
            .map(|ty| quote! { <#ty as ffier::FfiType>::C_TYPE_NAME })
            .collect();
        let param_name_str_refs: Vec<_> = m.param_name_strs.iter().collect::<Vec<_>>();

        let method_call = if let Some(tp) = &trait_path {
            quote! { <$struct_ty as $crate::#tp>::#method_name }
        } else {
            quote! { <$struct_ty>::#method_name }
        };

        match &m.ret {
            ReturnKind::Void => {
                let header_line = build_header_line(
                    quote! { "void" },
                    ffi_name_str,
                    &handle_type,
                    &param_c_type_exprs,
                    &param_name_str_refs,
                    None,
                );
                header_exprs.push(header_line);

                ffi_fns.push(quote! {
                    #[unsafe(no_mangle)]
                    pub unsafe extern "C" fn #ffi_name(
                        handle: *mut core::ffi::c_void,
                        #(#ffi_params),*
                    ) {
                        let obj = unsafe { #cast };
                        #method_call(obj, #(#converted_args),*);
                    }
                });
            }
            ReturnKind::Value(ty) => {
                let header_line = build_header_line(
                    quote! { <#ty as ffier::FfiType>::C_TYPE_NAME },
                    ffi_name_str,
                    &handle_type,
                    &param_c_type_exprs,
                    &param_name_str_refs,
                    None,
                );
                header_exprs.push(header_line);

                ffi_fns.push(quote! {
                    #[unsafe(no_mangle)]
                    pub unsafe extern "C" fn #ffi_name(
                        handle: *mut core::ffi::c_void,
                        #(#ffi_params),*
                    ) -> <#ty as ffier::FfiType>::CRepr {
                        let obj = unsafe { #cast };
                        let result = #method_call(obj, #(#converted_args),*);
                        <#ty as ffier::FfiType>::into_c(result)
                    }
                });
            }
            ReturnKind::Result {
                ok_ty,
                err_ty: _,
                err_ident,
            } => {
                let out_c_type = ok_ty.as_ref().map(|ty| {
                    quote! { <#ty as ffier::FfiType>::C_TYPE_NAME }
                });

                let header_line = build_header_line(
                    quote! { #err_ident },
                    ffi_name_str,
                    &handle_type,
                    &param_c_type_exprs,
                    &param_name_str_refs,
                    out_c_type.as_ref(),
                );
                header_exprs.push(header_line);

                let ok_branch = if let Some(ok) = ok_ty {
                    quote! {
                        Ok(val) => {
                            unsafe { out.write(<#ok as ffier::FfiType>::into_c(val)) };
                            ffier::FfierError::ok()
                        }
                    }
                } else {
                    quote! {
                        Ok(()) => ffier::FfierError::ok(),
                    }
                };

                let out_ffi_param = ok_ty.as_ref().map(|ok| {
                    quote! { out: *mut <#ok as ffier::FfiType>::CRepr, }
                });

                ffi_fns.push(quote! {
                    #[unsafe(no_mangle)]
                    pub unsafe extern "C" fn #ffi_name(
                        handle: *mut core::ffi::c_void,
                        #(#ffi_params,)*
                        #out_ffi_param
                    ) -> ffier::FfierError {
                        let obj = unsafe { #cast };
                        match #method_call(obj, #(#converted_args),*) {
                            #ok_branch
                            Err(e) => ffier::FfierError::from_err(e),
                        }
                    }
                });
            }
        }
    }

    // create / destroy
    let create_name = format_ident!("{struct_lower}_create");
    let destroy_name = format_ident!("{struct_lower}_destroy");
    let create_str = create_name.to_string();
    let destroy_str = destroy_name.to_string();

    header_exprs.push(quote! { "" });
    header_exprs.push(quote! { concat!(#struct_name, "Handle ", #create_str, "(void);") });
    header_exprs.push(
        quote! { concat!("void ", #destroy_str, "(", #struct_name, "Handle handle);") },
    );

    ffi_fns.push(quote! {
        #[unsafe(no_mangle)]
        pub extern "C" fn #create_name() -> *mut core::ffi::c_void {
            let obj = Box::new(<$struct_ty>::default());
            Box::into_raw(obj) as *mut core::ffi::c_void
        }
    });

    ffi_fns.push(quote! {
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn #destroy_name(handle: *mut core::ffi::c_void) {
            if !handle.is_null() {
                drop(unsafe { Box::from_raw(handle as *mut $struct_ty) });
            }
        }
    });

    let header_fn_name = format_ident!("{struct_lower}__header");
    let num_lines = header_exprs.len();
    let bridge_macro_name = format_ident!("{struct_lower}_ffier");

    let reexport_items: Vec<_> = reexport_types
        .iter()
        .zip(reexport_aliases.iter())
        .map(|(ty, alias)| quote! { pub type #alias = super::#ty; })
        .collect();

    let output = quote! {
        #impl_block

        #[doc(hidden)]
        pub mod #helper_mod_name {
            #(#reexport_items)*
        }

        #[macro_export]
        macro_rules! #bridge_macro_name {
            ($struct_ty:ty) => {
                #(#ffi_fns)*

                pub fn #header_fn_name() -> String {
                    let lines: [String; #num_lines] = [
                        #(#header_exprs .to_string()),*
                    ];
                    lines.join("\n")
                }
            };
        }
    };

    output.into()
}

fn build_header_line(
    c_ret_expr: proc_macro2::TokenStream,
    ffi_name_str: &str,
    handle_type: &str,
    param_c_type_exprs: &[proc_macro2::TokenStream],
    param_name_strs: &[&String],
    out_param_c_type: Option<&proc_macro2::TokenStream>,
) -> proc_macro2::TokenStream {
    let out_snippet = out_param_c_type.map(|ct| {
        quote! {
            s.push_str(", ");
            s.push_str(#ct);
            s.push_str("* out");
        }
    });
    quote! {{
        let c_type_names: &[&str] = &[#(#param_c_type_exprs),*];
        let param_names: &[&str] = &[#(#param_name_strs),*];
        let mut s = String::new();
        s.push_str(#c_ret_expr);
        s.push(' ');
        s.push_str(#ffi_name_str);
        s.push('(');
        s.push_str(#handle_type);
        for (cty, name) in c_type_names.iter().zip(param_names.iter()) {
            s.push_str(", ");
            s.push_str(cty);
            s.push(' ');
            s.push_str(name);
        }
        #out_snippet
        s.push_str(");");
        s
    }}
}

fn extract_result_types(ty: &Type) -> Option<(Type, Type)> {
    let Type::Path(tp) = ty else { return None };
    let last = tp.path.segments.last()?;
    if last.ident != "Result" {
        return None;
    }
    let PathArguments::AngleBracketed(args) = &last.arguments else {
        return None;
    };
    let mut iter = args.args.iter();
    let GenericArgument::Type(ok_ty) = iter.next()? else {
        return None;
    };
    let GenericArgument::Type(err_ty) = iter.next()? else {
        return None;
    };
    Some((ok_ty.clone(), err_ty.clone()))
}

/// Extract the simple ident name from a type (e.g. `CalcError` → `"CalcError"`).
fn type_ident_name(ty: &Type) -> String {
    let Type::Path(tp) = ty else {
        return "Error".to_string();
    };
    tp.path
        .segments
        .last()
        .map(|s| s.ident.to_string())
        .unwrap_or_else(|| "Error".to_string())
}

fn is_unit_type(ty: &Type) -> bool {
    matches!(ty, Type::Tuple(t) if t.elems.is_empty())
}

/// `CalcError` → `calc_error`
fn camel_to_snake(s: &str) -> String {
    let mut out = String::new();
    for (i, ch) in s.chars().enumerate() {
        if ch.is_uppercase() {
            if i > 0 {
                out.push('_');
            }
            out.push(ch.to_ascii_lowercase());
        } else {
            out.push(ch);
        }
    }
    out
}

/// `CalcError` → `CALC_ERROR`
fn camel_to_upper_snake(s: &str) -> String {
    camel_to_snake(s).to_ascii_uppercase()
}

const PRIMITIVES: &[&str] = &[
    "i8", "i16", "i32", "i64", "u8", "u16", "u32", "u64", "isize", "usize", "bool", "f32", "f64",
];

fn type_tokens_for_macro(
    ty: &Type,
    reexport_types: &mut Vec<Type>,
    reexport_aliases: &mut Vec<syn::Ident>,
    counter: &mut u32,
    helper_mod: &syn::Ident,
) -> proc_macro2::TokenStream {
    if is_primitive(ty) {
        return quote! { #ty };
    }

    for (i, existing) in reexport_types.iter().enumerate() {
        if quote!(#existing).to_string() == quote!(#ty).to_string() {
            let alias = &reexport_aliases[i];
            return quote! { $crate::#helper_mod::#alias };
        }
    }

    let alias = format_ident!("_Type{counter}");
    *counter += 1;
    reexport_types.push(ty.clone());
    reexport_aliases.push(alias.clone());

    quote! { $crate::#helper_mod::#alias }
}

fn is_primitive(ty: &Type) -> bool {
    let Type::Path(tp) = ty else { return false };
    tp.path.segments.len() == 1
        && PRIMITIVES.contains(&tp.path.segments[0].ident.to_string().as_str())
}
