use proc_macro::TokenStream;
use quote::{format_ident, quote};
use syn::{FnArg, ImplItem, ItemImpl, Pat, ReturnType, Type, parse_macro_input};

/// Attribute macro placed on `impl Trait for Struct` blocks.
///
/// Preserves the impl and generates:
/// 1. A helper module `_ffier_{struct_lowercase}` that re-exports all types
///    used in method signatures (so the bridge macro can reference them).
/// 2. A `#[macro_export]` macro `{struct_lowercase}_ffier!()` that generates
///    all `extern "C"` wrapper functions and a header function.
#[proc_macro_attribute]
pub fn reflect(_attr: TokenStream, item: TokenStream) -> TokenStream {
    let input = parse_macro_input!(item as ItemImpl);
    let impl_block = input.clone();

    let Type::Path(ref struct_path) = *input.self_ty else {
        return syn::Error::new_spanned(&input.self_ty, "expected a named struct type")
            .to_compile_error()
            .into();
    };
    let struct_ident = struct_path.path.get_ident().expect("expected simple struct name");
    let struct_name = struct_ident.to_string();
    let struct_lower = struct_name.to_lowercase();

    let trait_path = input.trait_.as_ref().map(|(_, path, _)| path);

    let mut ffi_fns = Vec::new();
    let mut header_exprs: Vec<proc_macro2::TokenStream> = Vec::new();

    header_exprs.push(quote! { concat!("/* Auto-generated by ffier for ", #struct_name, " */") });
    header_exprs.push(quote! { "#pragma once" });
    header_exprs.push(quote! { "#include <stdint.h>" });
    header_exprs.push(quote! { "#include <stdbool.h>" });
    header_exprs.push(quote! { "" });
    header_exprs.push(quote! { concat!("typedef void* ", #struct_name, "Handle;") });
    header_exprs.push(quote! { "" });

    // Collect all non-primitive types used in signatures for re-export
    let mut reexport_types: Vec<Type> = Vec::new();
    let mut reexport_aliases: Vec<syn::Ident> = Vec::new();

    // Helper: get an alias ident for a type, and register it for re-export if needed.
    // Returns the token stream to use in the macro body.
    let helper_mod_name = format_ident!("_ffier_{struct_lower}");

    struct MethodInfo {
        method_name: syn::Ident,
        ffi_name: syn::Ident,
        ffi_name_str: String,
        is_mut: bool,
        param_idents: Vec<syn::Ident>,
        param_name_strs: Vec<String>,
        // These are the tokens to use in the macro body (may reference helper mod)
        param_type_tokens: Vec<proc_macro2::TokenStream>,
        ret_type_tokens: Option<proc_macro2::TokenStream>,
    }

    let mut methods = Vec::new();
    let mut alias_counter = 0u32;

    for item in &input.items {
        let ImplItem::Fn(method) = item else { continue };
        let method_name = &method.sig.ident;
        let ffi_name = format_ident!("{struct_lower}_{method_name}");
        let ffi_name_str = ffi_name.to_string();

        let self_arg = method.sig.inputs.first();
        if !matches!(self_arg, Some(FnArg::Receiver(_))) {
            continue;
        }
        let receiver = match self_arg.unwrap() {
            FnArg::Receiver(r) => r,
            _ => unreachable!(),
        };
        let is_mut = receiver.mutability.is_some();

        let mut param_idents = Vec::new();
        let mut param_name_strs = Vec::new();
        let mut param_type_tokens = Vec::new();

        for arg in method.sig.inputs.iter().skip(1) {
            let FnArg::Typed(pat_ty) = arg else { continue };
            let Pat::Ident(pat_ident) = &*pat_ty.pat else { continue };
            param_idents.push(pat_ident.ident.clone());
            param_name_strs.push(pat_ident.ident.to_string());

            let ty = &*pat_ty.ty;
            let tokens = type_tokens_for_macro(
                ty,
                &mut reexport_types,
                &mut reexport_aliases,
                &mut alias_counter,
                &helper_mod_name,
            );
            param_type_tokens.push(tokens);
        }

        let ret_type_tokens = match &method.sig.output {
            ReturnType::Default => None,
            ReturnType::Type(_, ty) => Some(type_tokens_for_macro(
                ty,
                &mut reexport_types,
                &mut reexport_aliases,
                &mut alias_counter,
                &helper_mod_name,
            )),
        };

        methods.push(MethodInfo {
            method_name: method_name.clone(),
            ffi_name,
            ffi_name_str,
            is_mut,
            param_idents,
            param_name_strs,
            param_type_tokens,
            ret_type_tokens,
        });
    }

    for m in &methods {
        let ffi_name_str = &m.ffi_name_str;
        let ffi_name = &m.ffi_name;
        let method_name = &m.method_name;

        // Header line
        let c_ret_expr = match &m.ret_type_tokens {
            Some(ty) => quote! { <#ty as ffier::FfiType>::C_TYPE_NAME },
            None => quote! { "void" },
        };
        let param_c_type_exprs: Vec<_> = m.param_type_tokens.iter().map(|ty| {
            quote! { <#ty as ffier::FfiType>::C_TYPE_NAME }
        }).collect();
        let param_name_str_refs: Vec<_> = m.param_name_strs.iter().collect::<Vec<_>>();
        let handle_type = format!("{struct_name}Handle handle");

        let header_line_expr = if m.param_type_tokens.is_empty() {
            quote! {{
                let mut s = String::new();
                s.push_str(#c_ret_expr);
                s.push(' ');
                s.push_str(#ffi_name_str);
                s.push('(');
                s.push_str(#handle_type);
                s.push_str(");");
                s
            }}
        } else {
            quote! {{
                let c_type_names: &[&str] = &[#(#param_c_type_exprs),*];
                let param_names: &[&str] = &[#(#param_name_str_refs),*];
                let mut s = String::new();
                s.push_str(#c_ret_expr);
                s.push(' ');
                s.push_str(#ffi_name_str);
                s.push('(');
                s.push_str(#handle_type);
                for (cty, name) in c_type_names.iter().zip(param_names.iter()) {
                    s.push_str(", ");
                    s.push_str(cty);
                    s.push(' ');
                    s.push_str(name);
                }
                s.push_str(");");
                s
            }}
        };
        header_exprs.push(header_line_expr);

        // FFI function
        let cast = if m.is_mut {
            quote! { &mut *(handle as *mut $struct_ty) }
        } else {
            quote! { &*(handle as *const $struct_ty) }
        };

        let ffi_params: Vec<_> = m.param_idents.iter().zip(m.param_type_tokens.iter()).map(|(id, ty)| {
            quote! { #id: <#ty as ffier::FfiType>::CRepr }
        }).collect();

        let converted_args: Vec<_> = m.param_idents.iter().zip(m.param_type_tokens.iter()).map(|(id, ty)| {
            quote! { <#ty as ffier::FfiType>::from_c(#id) }
        }).collect();

        let method_call = if let Some(tp) = &trait_path {
            quote! { <$struct_ty as $crate::#tp>::#method_name }
        } else {
            quote! { <$struct_ty>::#method_name }
        };

        let (body, ret_annotation) = match &m.ret_type_tokens {
            Some(ty) => (
                quote! {
                    let result = #method_call(obj, #(#converted_args),*);
                    <#ty as ffier::FfiType>::into_c(result)
                },
                quote! { -> <#ty as ffier::FfiType>::CRepr },
            ),
            None => (
                quote! { #method_call(obj, #(#converted_args),*); },
                quote! {},
            ),
        };

        ffi_fns.push(quote! {
            #[unsafe(no_mangle)]
            pub unsafe extern "C" fn #ffi_name(handle: *mut core::ffi::c_void, #(#ffi_params),*) #ret_annotation {
                let obj = unsafe { #cast };
                #body
            }
        });
    }

    // create / destroy
    let create_name = format_ident!("{struct_lower}_create");
    let destroy_name = format_ident!("{struct_lower}_destroy");
    let create_str = create_name.to_string();
    let destroy_str = destroy_name.to_string();

    header_exprs.push(quote! { "" });
    header_exprs.push(quote! { concat!(#struct_name, "Handle ", #create_str, "(void);") });
    header_exprs.push(quote! { concat!("void ", #destroy_str, "(", #struct_name, "Handle handle);") });

    ffi_fns.push(quote! {
        #[unsafe(no_mangle)]
        pub extern "C" fn #create_name() -> *mut core::ffi::c_void {
            let obj = Box::new(<$struct_ty>::default());
            Box::into_raw(obj) as *mut core::ffi::c_void
        }
    });

    ffi_fns.push(quote! {
        #[unsafe(no_mangle)]
        pub unsafe extern "C" fn #destroy_name(handle: *mut core::ffi::c_void) {
            if !handle.is_null() {
                drop(unsafe { Box::from_raw(handle as *mut $struct_ty) });
            }
        }
    });

    let header_fn_name = format_ident!("{struct_lower}__header");
    let num_lines = header_exprs.len();
    let bridge_macro_name = format_ident!("{struct_lower}_ffier");

    // Generate the re-export helper module
    let reexport_items: Vec<_> = reexport_types.iter().zip(reexport_aliases.iter()).map(|(ty, alias)| {
        quote! { pub type #alias = super::#ty; }
    }).collect();

    let output = quote! {
        #impl_block

        #[doc(hidden)]
        pub mod #helper_mod_name {
            #(#reexport_items)*
        }

        #[macro_export]
        macro_rules! #bridge_macro_name {
            ($struct_ty:ty) => {
                #(#ffi_fns)*

                pub fn #header_fn_name() -> String {
                    let lines: [String; #num_lines] = [
                        #(#header_exprs .to_string()),*
                    ];
                    lines.join("\n")
                }
            };
        }
    };

    output.into()
}

const PRIMITIVES: &[&str] = &[
    "i8", "i16", "i32", "i64", "u8", "u16", "u32", "u64",
    "isize", "usize", "bool", "f32", "f64",
];

/// For a type used in a method signature, returns token stream suitable for
/// use inside the generated `macro_rules!` body.
///
/// Primitive types are emitted as-is. Non-primitive types are re-exported
/// through a helper module using `$crate::_ffier_xxx::AliasN` so they
/// resolve correctly when the macro is expanded in another crate.
fn type_tokens_for_macro(
    ty: &Type,
    reexport_types: &mut Vec<Type>,
    reexport_aliases: &mut Vec<syn::Ident>,
    counter: &mut u32,
    helper_mod: &syn::Ident,
) -> proc_macro2::TokenStream {
    if is_primitive(ty) {
        return quote! { #ty };
    }

    // Check if we already have this type re-exported
    for (i, existing) in reexport_types.iter().enumerate() {
        if quote!(#existing).to_string() == quote!(#ty).to_string() {
            let alias = &reexport_aliases[i];
            return quote! { $crate::#helper_mod::#alias };
        }
    }

    let alias = format_ident!("_Type{counter}");
    *counter += 1;
    reexport_types.push(ty.clone());
    reexport_aliases.push(alias.clone());

    quote! { $crate::#helper_mod::#alias }
}

fn is_primitive(ty: &Type) -> bool {
    let Type::Path(tp) = ty else { return false };
    tp.path.segments.len() == 1
        && PRIMITIVES.contains(&tp.path.segments[0].ident.to_string().as_str())
}
